/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.daos;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Converter;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zeroagent.infra.dal.tables.AiTaskCreation;
import org.zeroagent.infra.dal.tables.records.AiTaskCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class AiTaskCreationDao extends DAOImpl<AiTaskCreationRecord, org.zeroagent.infra.dal.tables.pojos.AiTaskCreation, Long> {

    /**
     * Create a new AiTaskCreationDao without any configuration
     */
    public AiTaskCreationDao() {
        super(AiTaskCreation.AI_TASK_CREATION, org.zeroagent.infra.dal.tables.pojos.AiTaskCreation.class);
    }

    /**
     * Create a new AiTaskCreationDao with an attached configuration
     */
    @Autowired
    public AiTaskCreationDao(Configuration configuration) {
        super(AiTaskCreation.AI_TASK_CREATION, org.zeroagent.infra.dal.tables.pojos.AiTaskCreation.class, configuration);
    }

    @Override
    public Long getId(org.zeroagent.infra.dal.tables.pojos.AiTaskCreation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchById(Long... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.AiTaskCreation fetchOneById(Long value) {
        return fetchOne(AiTaskCreation.AI_TASK_CREATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchOptionalById(Long value) {
        return fetchOptional(AiTaskCreation.AI_TASK_CREATION.ID, value);
    }

    /**
     * Fetch records that have <code>owner_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfOwnerId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.OWNER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByOwnerId(Long... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.OWNER_ID, values);
    }

    /**
     * Fetch records that have <code>owner_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfOwnerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.OWNER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>owner_name IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByOwnerName(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.OWNER_NAME, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfCreatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByCreatedAt(ZonedDateTime... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfUpdatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByUpdatedAt(ZonedDateTime... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>task_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfTaskName(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.TASK_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>task_name IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByTaskName(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.TASK_NAME, values);
    }

    /**
     * Fetch records that have <code>task_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfTaskType(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.TASK_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>task_type IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByTaskType(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.TASK_TYPE, values);
    }

    /**
     * Fetch records that have <code>biz_status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_status IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizStatus(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_STATUS, values);
    }

    /**
     * Fetch records that have <code>biz_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizType(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_type IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizType(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_TYPE, values);
    }

    /**
     * Fetch records that have <code>biz_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_no IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizNo(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_NO, values);
    }

    /**
     * Fetch records that have <code>sub_biz_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfSubBizNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.SUB_BIZ_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sub_biz_no IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchBySubBizNo(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.SUB_BIZ_NO, values);
    }

    /**
     * Fetch records that have <code>task_status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfTaskStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.TASK_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>task_status IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByTaskStatus(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.TASK_STATUS, values);
    }

    /**
     * Fetch records that have <code>exec_status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfExecStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.EXEC_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exec_status IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByExecStatus(String... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.EXEC_STATUS, values);
    }

    /**
     * Fetch records that have <code>priority BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfPriority(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.PRIORITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>priority IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByPriority(Integer... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.PRIORITY, values);
    }

    /**
     * Fetch records that have <code>sharding BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfSharding(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.SHARDING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sharding IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchBySharding(Integer... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.SHARDING, values);
    }

    /**
     * Fetch records that have <code>start_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfStartAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.START_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByStartAt(ZonedDateTime... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.START_AT, values);
    }

    /**
     * Fetch records that have <code>finished_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfFinishedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.FINISHED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>finished_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByFinishedAt(ZonedDateTime... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.FINISHED_AT, values);
    }

    /**
     * Fetch records that have <code>biz_params BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizParams(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_PARAMS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_params IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizParams(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_PARAMS, values);
    }

    /**
     * Fetch records that have <code>biz_exec_info BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizExecInfo(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_EXEC_INFO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_exec_info IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizExecInfo(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_EXEC_INFO, values);
    }

    /**
     * Fetch records that have <code>biz_result BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfBizResult(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.BIZ_RESULT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_result IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByBizResult(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.BIZ_RESULT, values);
    }

    /**
     * Fetch records that have <code>sys_params BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfSysParams(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.SYS_PARAMS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sys_params IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchBySysParams(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.SYS_PARAMS, values);
    }

    /**
     * Fetch records that have <code>exec_info BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfExecInfo(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.EXEC_INFO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>exec_info IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchByExecInfo(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.EXEC_INFO, values);
    }

    /**
     * Fetch records that have <code>sys_result BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchRangeOfSysResult(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AiTaskCreation.AI_TASK_CREATION.SYS_RESULT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sys_result IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.AiTaskCreation> fetchBySysResult(JSONB... values) {
        return fetch(AiTaskCreation.AI_TASK_CREATION.SYS_RESULT, values);
    }
}
