/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.daos;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zeroagent.infra.dal.tables.CardInformationCreation;
import org.zeroagent.infra.dal.tables.records.CardInformationCreationRecord;


/**
 * OCG卡牌基础信息表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class CardInformationCreationDao extends DAOImpl<CardInformationCreationRecord, org.zeroagent.infra.dal.tables.pojos.CardInformationCreation, Long> {

    /**
     * Create a new CardInformationCreationDao without any configuration
     */
    public CardInformationCreationDao() {
        super(CardInformationCreation.CARD_INFORMATION_CREATION, org.zeroagent.infra.dal.tables.pojos.CardInformationCreation.class);
    }

    /**
     * Create a new CardInformationCreationDao with an attached configuration
     */
    @Autowired
    public CardInformationCreationDao(Configuration configuration) {
        super(CardInformationCreation.CARD_INFORMATION_CREATION, org.zeroagent.infra.dal.tables.pojos.CardInformationCreation.class, configuration);
    }

    @Override
    public Long getId(org.zeroagent.infra.dal.tables.pojos.CardInformationCreation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchById(Long... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.CardInformationCreation fetchOneById(Long value) {
        return fetchOne(CardInformationCreation.CARD_INFORMATION_CREATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchOptionalById(Long value) {
        return fetchOptional(CardInformationCreation.CARD_INFORMATION_CREATION.ID, value);
    }

    /**
     * Fetch records that have <code>passcode BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfPasscode(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>passcode IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByPasscode(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE, values);
    }

    /**
     * Fetch a unique record that has <code>passcode = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.CardInformationCreation fetchOneByPasscode(String value) {
        return fetchOne(CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE, value);
    }

    /**
     * Fetch a unique record that has <code>passcode = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchOptionalByPasscode(String value) {
        return fetchOptional(CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByName(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.NAME, values);
    }

    /**
     * Fetch records that have <code>attribution BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfAttribution(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.ATTRIBUTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attribution IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByAttribution(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.ATTRIBUTION, values);
    }

    /**
     * Fetch records that have <code>race BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfRace(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.RACE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>race IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByRace(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.RACE, values);
    }

    /**
     * Fetch records that have <code>atk BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfAtk(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.ATK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>atk IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByAtk(Integer... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.ATK, values);
    }

    /**
     * Fetch records that have <code>def BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfDef(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.DEF, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>def IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByDef(Integer... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.DEF, values);
    }

    /**
     * Fetch records that have <code>card_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfCardType(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.CARD_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>card_type IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByCardType(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.CARD_TYPE, values);
    }

    /**
     * Fetch records that have <code>card_subtype BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfCardSubtype(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.CARD_SUBTYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>card_subtype IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByCardSubtype(JSONB... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.CARD_SUBTYPE, values);
    }

    /**
     * Fetch records that have <code>monster_level BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfMonsterLevel(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.MONSTER_LEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>monster_level IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByMonsterLevel(Short... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.MONSTER_LEVEL, values);
    }

    /**
     * Fetch records that have <code>monster_rank BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfMonsterRank(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.MONSTER_RANK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>monster_rank IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByMonsterRank(Short... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.MONSTER_RANK, values);
    }

    /**
     * Fetch records that have <code>link_rating BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfLinkRating(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.LINK_RATING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>link_rating IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByLinkRating(Short... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.LINK_RATING, values);
    }

    /**
     * Fetch records that have <code>pendulum_scale BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfPendulumScale(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.PENDULUM_SCALE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>pendulum_scale IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByPendulumScale(Short... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.PENDULUM_SCALE, values);
    }

    /**
     * Fetch records that have <code>pendulum_effect BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfPendulumEffect(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.PENDULUM_EFFECT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>pendulum_effect IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByPendulumEffect(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.PENDULUM_EFFECT, values);
    }

    /**
     * Fetch records that have <code>effect BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfEffect(String lowerInclusive, String upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.EFFECT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>effect IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByEffect(String... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.EFFECT, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfUpdatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByUpdatedAt(OffsetDateTime... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>graph_sync_status BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfGraphSyncStatus(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.GRAPH_SYNC_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>graph_sync_status IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByGraphSyncStatus(Short... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.GRAPH_SYNC_STATUS, values);
    }

    /**
     * Fetch records that have <code>biz_response BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfBizResponse(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.BIZ_RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>biz_response IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByBizResponse(JSONB... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.BIZ_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>archetype BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchRangeOfArchetype(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(CardInformationCreation.CARD_INFORMATION_CREATION.ARCHETYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>archetype IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.CardInformationCreation> fetchByArchetype(JSONB... values) {
        return fetch(CardInformationCreation.CARD_INFORMATION_CREATION.ARCHETYPE, values);
    }
}
