/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.daos;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Converter;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zeroagent.infra.dal.tables.ConversationCreation;
import org.zeroagent.infra.dal.tables.records.ConversationCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ConversationCreationDao extends DAOImpl<ConversationCreationRecord, org.zeroagent.infra.dal.tables.pojos.ConversationCreation, Long> {

    /**
     * Create a new ConversationCreationDao without any configuration
     */
    public ConversationCreationDao() {
        super(ConversationCreation.CONVERSATION_CREATION, org.zeroagent.infra.dal.tables.pojos.ConversationCreation.class);
    }

    /**
     * Create a new ConversationCreationDao with an attached configuration
     */
    @Autowired
    public ConversationCreationDao(Configuration configuration) {
        super(ConversationCreation.CONVERSATION_CREATION, org.zeroagent.infra.dal.tables.pojos.ConversationCreation.class, configuration);
    }

    @Override
    public Long getId(org.zeroagent.infra.dal.tables.pojos.ConversationCreation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ConversationCreation.CONVERSATION_CREATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchById(Long... values) {
        return fetch(ConversationCreation.CONVERSATION_CREATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.ConversationCreation fetchOneById(Long value) {
        return fetchOne(ConversationCreation.CONVERSATION_CREATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchOptionalById(Long value) {
        return fetchOptional(ConversationCreation.CONVERSATION_CREATION.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchRangeOfCreatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(ConversationCreation.CONVERSATION_CREATION.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchByCreatedAt(ZonedDateTime... values) {
        return fetch(ConversationCreation.CONVERSATION_CREATION.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchRangeOfUpdatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(ConversationCreation.CONVERSATION_CREATION.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchByUpdatedAt(ZonedDateTime... values) {
        return fetch(ConversationCreation.CONVERSATION_CREATION.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>uid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchRangeOfUid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ConversationCreation.CONVERSATION_CREATION.UID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchByUid(Long... values) {
        return fetch(ConversationCreation.CONVERSATION_CREATION.UID, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(ConversationCreation.CONVERSATION_CREATION.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationCreation> fetchByTitle(String... values) {
        return fetch(ConversationCreation.CONVERSATION_CREATION.TITLE, values);
    }
}
