/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.daos;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Converter;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;
import org.zeroagent.infra.dal.tables.records.ConversationMessageCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ConversationMessageCreationDao extends DAOImpl<ConversationMessageCreationRecord, org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation, Long> {

    /**
     * Create a new ConversationMessageCreationDao without any configuration
     */
    public ConversationMessageCreationDao() {
        super(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION, org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation.class);
    }

    /**
     * Create a new ConversationMessageCreationDao with an attached
     * configuration
     */
    @Autowired
    public ConversationMessageCreationDao(Configuration configuration) {
        super(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION, org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation.class, configuration);
    }

    @Override
    public Long getId(org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchById(Long... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation fetchOneById(Long value) {
        return fetchOne(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchOptionalById(Long value) {
        return fetchOptional(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfCreatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByCreatedAt(ZonedDateTime... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfUpdatedAt(ZonedDateTime lowerInclusive, ZonedDateTime upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByUpdatedAt(ZonedDateTime... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>uid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfUid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.UID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByUid(Long... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.UID, values);
    }

    /**
     * Fetch records that have <code>conversation_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfConversationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CONVERSATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>conversation_id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByConversationId(Long... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CONVERSATION_ID, values);
    }

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfRole(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ROLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByRole(JSONB... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ROLE, values);
    }

    /**
     * Fetch records that have <code>content BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfContent(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByContent(JSONB... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CONTENT, values);
    }

    /**
     * Fetch records that have <code>reasoning_content BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchRangeOfReasoningContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.REASONING_CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>reasoning_content IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation> fetchByReasoningContent(String... values) {
        return fetch(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.REASONING_CONTENT, values);
    }
}
