/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.daos;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zeroagent.infra.dal.tables.GraphSyncErrorLog;
import org.zeroagent.infra.dal.tables.records.GraphSyncErrorLogRecord;


/**
 * Agent 图谱抽取错误与幻觉死信队列
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class GraphSyncErrorLogDao extends DAOImpl<GraphSyncErrorLogRecord, org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog, Long> {

    /**
     * Create a new GraphSyncErrorLogDao without any configuration
     */
    public GraphSyncErrorLogDao() {
        super(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG, org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog.class);
    }

    /**
     * Create a new GraphSyncErrorLogDao with an attached configuration
     */
    @Autowired
    public GraphSyncErrorLogDao(Configuration configuration) {
        super(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG, org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog.class, configuration);
    }

    @Override
    public Long getId(org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchById(Long... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog fetchOneById(Long value) {
        return fetchOne(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchOptionalById(Long value) {
        return fetchOptional(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>source_card_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfSourceCardId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.SOURCE_CARD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source_card_id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchBySourceCardId(Long... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.SOURCE_CARD_ID, values);
    }

    /**
     * Fetch records that have <code>source_card_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfSourceCardName(String lowerInclusive, String upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.SOURCE_CARD_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>source_card_name IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchBySourceCardName(String... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.SOURCE_CARD_NAME, values);
    }

    /**
     * Fetch records that have <code>llm_raw_response BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfLlmRawResponse(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.LLM_RAW_RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>llm_raw_response IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByLlmRawResponse(JSONB... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.LLM_RAW_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>error_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfErrorType(String lowerInclusive, String upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ERROR_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>error_type IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByErrorType(String... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ERROR_TYPE, values);
    }

    /**
     * Fetch records that have <code>error_message BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfErrorMessage(String lowerInclusive, String upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ERROR_MESSAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>error_message IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByErrorMessage(String... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ERROR_MESSAGE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfUpdatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByUpdatedAt(OffsetDateTime... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfStatus(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByStatus(Short... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.STATUS, values);
    }

    /**
     * Fetch records that have <code>target_card_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfTargetCardId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.TARGET_CARD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>target_card_id IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByTargetCardId(Long... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.TARGET_CARD_ID, values);
    }

    /**
     * Fetch records that have <code>target_card_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchRangeOfTargetCardName(String lowerInclusive, String upperInclusive) {
        return fetchRange(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.TARGET_CARD_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>target_card_name IN (values)</code>
     */
    public List<org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog> fetchByTargetCardName(String... values) {
        return fetch(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.TARGET_CARD_NAME, values);
    }
}
