/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.zeroagent.infra.dal.Indexes;
import org.zeroagent.infra.dal.Keys;
import org.zeroagent.infra.dal.Public;
import org.zeroagent.infra.dal.tables.records.AiTaskCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTaskCreation extends TableImpl<AiTaskCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ai_task_creation</code>
     */
    public static final AiTaskCreation AI_TASK_CREATION = new AiTaskCreation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiTaskCreationRecord> getRecordType() {
        return AiTaskCreationRecord.class;
    }

    /**
     * The column <code>public.ai_task_creation.id</code>.
     */
    public final TableField<AiTaskCreationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ai_task_creation.owner_id</code>.
     */
    public final TableField<AiTaskCreationRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.ai_task_creation.owner_name</code>.
     */
    public final TableField<AiTaskCreationRecord, String> OWNER_NAME = createField(DSL.name("owner_name"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.ai_task_creation.created_at</code>.
     */
    public final TableField<AiTaskCreationRecord, ZonedDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.ai_task_creation.updated_at</code>.
     */
    public final TableField<AiTaskCreationRecord, ZonedDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.ai_task_creation.task_name</code>.
     */
    public final TableField<AiTaskCreationRecord, String> TASK_NAME = createField(DSL.name("task_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.ai_task_creation.task_type</code>.
     */
    public final TableField<AiTaskCreationRecord, String> TASK_TYPE = createField(DSL.name("task_type"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.ai_task_creation.biz_status</code>.
     */
    public final TableField<AiTaskCreationRecord, String> BIZ_STATUS = createField(DSL.name("biz_status"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.ai_task_creation.biz_type</code>.
     */
    public final TableField<AiTaskCreationRecord, String> BIZ_TYPE = createField(DSL.name("biz_type"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.ai_task_creation.biz_no</code>.
     */
    public final TableField<AiTaskCreationRecord, String> BIZ_NO = createField(DSL.name("biz_no"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.ai_task_creation.sub_biz_no</code>.
     */
    public final TableField<AiTaskCreationRecord, String> SUB_BIZ_NO = createField(DSL.name("sub_biz_no"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.ai_task_creation.task_status</code>.
     */
    public final TableField<AiTaskCreationRecord, String> TASK_STATUS = createField(DSL.name("task_status"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.ai_task_creation.exec_status</code>.
     */
    public final TableField<AiTaskCreationRecord, String> EXEC_STATUS = createField(DSL.name("exec_status"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.ai_task_creation.priority</code>.
     */
    public final TableField<AiTaskCreationRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("100"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ai_task_creation.sharding</code>.
     */
    public final TableField<AiTaskCreationRecord, Integer> SHARDING = createField(DSL.name("sharding"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ai_task_creation.start_at</code>.
     */
    public final TableField<AiTaskCreationRecord, ZonedDateTime> START_AT = createField(DSL.name("start_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.ai_task_creation.finished_at</code>.
     */
    public final TableField<AiTaskCreationRecord, ZonedDateTime> FINISHED_AT = createField(DSL.name("finished_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.ai_task_creation.biz_params</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> BIZ_PARAMS = createField(DSL.name("biz_params"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.ai_task_creation.biz_exec_info</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> BIZ_EXEC_INFO = createField(DSL.name("biz_exec_info"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.ai_task_creation.biz_result</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> BIZ_RESULT = createField(DSL.name("biz_result"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.ai_task_creation.sys_params</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> SYS_PARAMS = createField(DSL.name("sys_params"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.ai_task_creation.exec_info</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> EXEC_INFO = createField(DSL.name("exec_info"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.ai_task_creation.sys_result</code>.
     */
    public final TableField<AiTaskCreationRecord, JSONB> SYS_RESULT = createField(DSL.name("sys_result"), SQLDataType.JSONB, this, "");

    private AiTaskCreation(Name alias, Table<AiTaskCreationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiTaskCreation(Name alias, Table<AiTaskCreationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ai_task_creation</code> table reference
     */
    public AiTaskCreation(String alias) {
        this(DSL.name(alias), AI_TASK_CREATION);
    }

    /**
     * Create an aliased <code>public.ai_task_creation</code> table reference
     */
    public AiTaskCreation(Name alias) {
        this(alias, AI_TASK_CREATION);
    }

    /**
     * Create a <code>public.ai_task_creation</code> table reference
     */
    public AiTaskCreation() {
        this(DSL.name("ai_task_creation"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AI_TASK_CREATION_BIZ, Indexes.IDX_AI_TASK_CREATION_CREATED_AT, Indexes.IDX_AI_TASK_CREATION_EXEC_STATUS, Indexes.IDX_AI_TASK_CREATION_OWNER_ID, Indexes.IDX_AI_TASK_CREATION_TASK_STATUS);
    }

    @Override
    public UniqueKey<AiTaskCreationRecord> getPrimaryKey() {
        return Keys.AI_TASK_CREATION_PKEY;
    }

    @Override
    public AiTaskCreation as(String alias) {
        return new AiTaskCreation(DSL.name(alias), this);
    }

    @Override
    public AiTaskCreation as(Name alias) {
        return new AiTaskCreation(alias, this);
    }

    @Override
    public AiTaskCreation as(Table<?> alias) {
        return new AiTaskCreation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTaskCreation rename(String name) {
        return new AiTaskCreation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTaskCreation rename(Name name) {
        return new AiTaskCreation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTaskCreation rename(Table<?> name) {
        return new AiTaskCreation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation where(Condition condition) {
        return new AiTaskCreation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTaskCreation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTaskCreation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTaskCreation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTaskCreation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTaskCreation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
