/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.zeroagent.infra.dal.Indexes;
import org.zeroagent.infra.dal.Keys;
import org.zeroagent.infra.dal.Public;
import org.zeroagent.infra.dal.tables.records.CardInformationCreationRecord;


/**
 * OCG卡牌基础信息表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardInformationCreation extends TableImpl<CardInformationCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.card_information_creation</code>
     */
    public static final CardInformationCreation CARD_INFORMATION_CREATION = new CardInformationCreation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardInformationCreationRecord> getRecordType() {
        return CardInformationCreationRecord.class;
    }

    /**
     * The column <code>public.card_information_creation.id</code>. 雪花算法主键
     */
    public final TableField<CardInformationCreationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "雪花算法主键");

    /**
     * The column <code>public.card_information_creation.passcode</code>.
     * 官方8位卡片密码
     */
    public final TableField<CardInformationCreationRecord, String> PASSCODE = createField(DSL.name("passcode"), SQLDataType.VARCHAR(15), this, "官方8位卡片密码");

    /**
     * The column <code>public.card_information_creation.name</code>. 卡片名称
     */
    public final TableField<CardInformationCreationRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false), this, "卡片名称");

    /**
     * The column <code>public.card_information_creation.attribution</code>. 属性
     * (光/暗/地/水/炎/风/神)
     */
    public final TableField<CardInformationCreationRecord, String> ATTRIBUTION = createField(DSL.name("attribution"), SQLDataType.VARCHAR(32), this, "属性 (光/暗/地/水/炎/风/神)");

    /**
     * The column <code>public.card_information_creation.race</code>. 种族
     * (龙/恶魔/魔法师等)
     */
    public final TableField<CardInformationCreationRecord, String> RACE = createField(DSL.name("race"), SQLDataType.VARCHAR(32), this, "种族 (龙/恶魔/魔法师等)");

    /**
     * The column <code>public.card_information_creation.atk</code>. 攻击力 (-1表示?)
     */
    public final TableField<CardInformationCreationRecord, Integer> ATK = createField(DSL.name("atk"), SQLDataType.INTEGER, this, "攻击力 (-1表示?)");

    /**
     * The column <code>public.card_information_creation.def</code>. 守备力 (-1表示?,
     * NULL表示无守备力)
     */
    public final TableField<CardInformationCreationRecord, Integer> DEF = createField(DSL.name("def"), SQLDataType.INTEGER, this, "守备力 (-1表示?, NULL表示无守备力)");

    /**
     * The column <code>public.card_information_creation.card_type</code>.
     */
    public final TableField<CardInformationCreationRecord, String> CARD_TYPE = createField(DSL.name("card_type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.card_information_creation.card_subtype</code>.
     * 卡牌特性的JSONB数组
     */
    public final TableField<CardInformationCreationRecord, JSONB> CARD_SUBTYPE = createField(DSL.name("card_subtype"), SQLDataType.JSONB, this, "卡牌特性的JSONB数组");

    /**
     * The column <code>public.card_information_creation.monster_level</code>.
     */
    public final TableField<CardInformationCreationRecord, Short> MONSTER_LEVEL = createField(DSL.name("monster_level"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.card_information_creation.monster_rank</code>.
     */
    public final TableField<CardInformationCreationRecord, Short> MONSTER_RANK = createField(DSL.name("monster_rank"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.card_information_creation.link_rating</code>.
     */
    public final TableField<CardInformationCreationRecord, Short> LINK_RATING = createField(DSL.name("link_rating"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.card_information_creation.pendulum_scale</code>.
     */
    public final TableField<CardInformationCreationRecord, Short> PENDULUM_SCALE = createField(DSL.name("pendulum_scale"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.card_information_creation.pendulum_effect</code>.
     * 灵摆区域专有效果
     */
    public final TableField<CardInformationCreationRecord, String> PENDULUM_EFFECT = createField(DSL.name("pendulum_effect"), SQLDataType.CLOB, this, "灵摆区域专有效果");

    /**
     * The column <code>public.card_information_creation.effect</code>.
     */
    public final TableField<CardInformationCreationRecord, String> EFFECT = createField(DSL.name("effect"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.card_information_creation.created_at</code>.
     */
    public final TableField<CardInformationCreationRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.card_information_creation.updated_at</code>.
     */
    public final TableField<CardInformationCreationRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public.card_information_creation.graph_sync_status</code>. 图谱同步状态:
     * 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常
     */
    public final TableField<CardInformationCreationRecord, Short> GRAPH_SYNC_STATUS = createField(DSL.name("graph_sync_status"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "图谱同步状态: 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常");

    /**
     * The column <code>public.card_information_creation.biz_response</code>.
     * 存储API返回完整响应体
     */
    public final TableField<CardInformationCreationRecord, JSONB> BIZ_RESPONSE = createField(DSL.name("biz_response"), SQLDataType.JSONB, this, "存储API返回完整响应体");

    /**
     * The column <code>public.card_information_creation.archetype</code>.
     * 存储卡牌字段
     */
    public final TableField<CardInformationCreationRecord, JSONB> ARCHETYPE = createField(DSL.name("archetype"), SQLDataType.JSONB, this, "存储卡牌字段");

    private CardInformationCreation(Name alias, Table<CardInformationCreationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CardInformationCreation(Name alias, Table<CardInformationCreationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("OCG卡牌基础信息表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.card_information_creation</code> table
     * reference
     */
    public CardInformationCreation(String alias) {
        this(DSL.name(alias), CARD_INFORMATION_CREATION);
    }

    /**
     * Create an aliased <code>public.card_information_creation</code> table
     * reference
     */
    public CardInformationCreation(Name alias) {
        this(alias, CARD_INFORMATION_CREATION);
    }

    /**
     * Create a <code>public.card_information_creation</code> table reference
     */
    public CardInformationCreation() {
        this(DSL.name("card_information_creation"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CARD_INFO_PASSCODE, Indexes.IDX_CARD_INFO_SYNC_STATUS, Indexes.TRGM_IDX_CARD_NAME);
    }

    @Override
    public UniqueKey<CardInformationCreationRecord> getPrimaryKey() {
        return Keys.CARD_INFORMATION_CREATION_PKEY;
    }

    @Override
    public List<UniqueKey<CardInformationCreationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CARD_INFORMATION_CREATION_PASSCODE_KEY);
    }

    @Override
    public CardInformationCreation as(String alias) {
        return new CardInformationCreation(DSL.name(alias), this);
    }

    @Override
    public CardInformationCreation as(Name alias) {
        return new CardInformationCreation(alias, this);
    }

    @Override
    public CardInformationCreation as(Table<?> alias) {
        return new CardInformationCreation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CardInformationCreation rename(String name) {
        return new CardInformationCreation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardInformationCreation rename(Name name) {
        return new CardInformationCreation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardInformationCreation rename(Table<?> name) {
        return new CardInformationCreation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation where(Condition condition) {
        return new CardInformationCreation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardInformationCreation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardInformationCreation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardInformationCreation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardInformationCreation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardInformationCreation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
