/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.zeroagent.infra.dal.Indexes;
import org.zeroagent.infra.dal.Keys;
import org.zeroagent.infra.dal.Public;
import org.zeroagent.infra.dal.tables.records.ConversationMessageCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationMessageCreation extends TableImpl<ConversationMessageCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.conversation_message_creation</code>
     */
    public static final ConversationMessageCreation CONVERSATION_MESSAGE_CREATION = new ConversationMessageCreation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConversationMessageCreationRecord> getRecordType() {
        return ConversationMessageCreationRecord.class;
    }

    /**
     * The column <code>public.conversation_message_creation.id</code>.
     */
    public final TableField<ConversationMessageCreationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.conversation_message_creation.created_at</code>.
     */
    public final TableField<ConversationMessageCreationRecord, ZonedDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.conversation_message_creation.updated_at</code>.
     */
    public final TableField<ConversationMessageCreationRecord, ZonedDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", Converter.ofNullable(OffsetDateTime.class, ZonedDateTime.class, java.time.ZonedDateTime::from, java.time.ZonedDateTime::toOffsetDateTime));

    /**
     * The column <code>public.conversation_message_creation.uid</code>.
     */
    public final TableField<ConversationMessageCreationRecord, Long> UID = createField(DSL.name("uid"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>public.conversation_message_creation.conversation_id</code>.
     */
    public final TableField<ConversationMessageCreationRecord, Long> CONVERSATION_ID = createField(DSL.name("conversation_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.conversation_message_creation.role</code>.
     */
    public final TableField<ConversationMessageCreationRecord, JSONB> ROLE = createField(DSL.name("role"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.conversation_message_creation.content</code>.
     */
    public final TableField<ConversationMessageCreationRecord, JSONB> CONTENT = createField(DSL.name("content"), SQLDataType.JSONB, this, "");

    /**
     * The column
     * <code>public.conversation_message_creation.reasoning_content</code>.
     */
    public final TableField<ConversationMessageCreationRecord, String> REASONING_CONTENT = createField(DSL.name("reasoning_content"), SQLDataType.CLOB, this, "");

    private ConversationMessageCreation(Name alias, Table<ConversationMessageCreationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConversationMessageCreation(Name alias, Table<ConversationMessageCreationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.conversation_message_creation</code> table
     * reference
     */
    public ConversationMessageCreation(String alias) {
        this(DSL.name(alias), CONVERSATION_MESSAGE_CREATION);
    }

    /**
     * Create an aliased <code>public.conversation_message_creation</code> table
     * reference
     */
    public ConversationMessageCreation(Name alias) {
        this(alias, CONVERSATION_MESSAGE_CREATION);
    }

    /**
     * Create a <code>public.conversation_message_creation</code> table
     * reference
     */
    public ConversationMessageCreation() {
        this(DSL.name("conversation_message_creation"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CONVERSATION_MESSAGE_CREATION_ID, Indexes.IDX_CONVERSATION_MESSAGE_CREATION_UID);
    }

    @Override
    public Identity<ConversationMessageCreationRecord, Long> getIdentity() {
        return (Identity<ConversationMessageCreationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConversationMessageCreationRecord> getPrimaryKey() {
        return Keys.CONVERSATION_MESSAGE_CREATION_PKEY;
    }

    @Override
    public ConversationMessageCreation as(String alias) {
        return new ConversationMessageCreation(DSL.name(alias), this);
    }

    @Override
    public ConversationMessageCreation as(Name alias) {
        return new ConversationMessageCreation(alias, this);
    }

    @Override
    public ConversationMessageCreation as(Table<?> alias) {
        return new ConversationMessageCreation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationMessageCreation rename(String name) {
        return new ConversationMessageCreation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationMessageCreation rename(Name name) {
        return new ConversationMessageCreation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationMessageCreation rename(Table<?> name) {
        return new ConversationMessageCreation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation where(Condition condition) {
        return new ConversationMessageCreation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationMessageCreation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationMessageCreation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationMessageCreation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationMessageCreation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationMessageCreation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
