/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.zeroagent.infra.dal.Indexes;
import org.zeroagent.infra.dal.Keys;
import org.zeroagent.infra.dal.Public;
import org.zeroagent.infra.dal.tables.records.ConversationCreationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationCreation extends TableImpl<ConversationCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.conversation_creation</code>
     */
    public static final ConversationCreation CONVERSATION_CREATION = new ConversationCreation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConversationCreationRecord> getRecordType() {
        return ConversationCreationRecord.class;
    }

    /**
     * The column <code>public.conversation_creation.id</code>.
     */
    public final TableField<ConversationCreationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.conversation_creation.created_at</code>.
     */
    public final TableField<ConversationCreationRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.conversation_creation.updated_at</code>.
     */
    public final TableField<ConversationCreationRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.conversation_creation.uid</code>.
     */
    public final TableField<ConversationCreationRecord, Long> UID = createField(DSL.name("uid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.conversation_creation.title</code>.
     */
    public final TableField<ConversationCreationRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    private ConversationCreation(Name alias, Table<ConversationCreationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConversationCreation(Name alias, Table<ConversationCreationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.conversation_creation</code> table
     * reference
     */
    public ConversationCreation(String alias) {
        this(DSL.name(alias), CONVERSATION_CREATION);
    }

    /**
     * Create an aliased <code>public.conversation_creation</code> table
     * reference
     */
    public ConversationCreation(Name alias) {
        this(alias, CONVERSATION_CREATION);
    }

    /**
     * Create a <code>public.conversation_creation</code> table reference
     */
    public ConversationCreation() {
        this(DSL.name("conversation_creation"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CONVERSATION_CREATION_UID);
    }

    @Override
    public Identity<ConversationCreationRecord, Long> getIdentity() {
        return (Identity<ConversationCreationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConversationCreationRecord> getPrimaryKey() {
        return Keys.CONVERSATION_CREATION_PKEY;
    }

    @Override
    public ConversationCreation as(String alias) {
        return new ConversationCreation(DSL.name(alias), this);
    }

    @Override
    public ConversationCreation as(Name alias) {
        return new ConversationCreation(alias, this);
    }

    @Override
    public ConversationCreation as(Table<?> alias) {
        return new ConversationCreation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationCreation rename(String name) {
        return new ConversationCreation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationCreation rename(Name name) {
        return new ConversationCreation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConversationCreation rename(Table<?> name) {
        return new ConversationCreation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation where(Condition condition) {
        return new ConversationCreation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationCreation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationCreation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationCreation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConversationCreation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConversationCreation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
