/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.zeroagent.infra.dal.Keys;
import org.zeroagent.infra.dal.Public;
import org.zeroagent.infra.dal.tables.records.GraphSyncErrorLogRecord;


/**
 * Agent 图谱抽取错误与幻觉死信队列
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GraphSyncErrorLog extends TableImpl<GraphSyncErrorLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.graph_sync_error_log</code>
     */
    public static final GraphSyncErrorLog GRAPH_SYNC_ERROR_LOG = new GraphSyncErrorLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GraphSyncErrorLogRecord> getRecordType() {
        return GraphSyncErrorLogRecord.class;
    }

    /**
     * The column <code>public.graph_sync_error_log.id</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.graph_sync_error_log.source_card_id</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, Long> SOURCE_CARD_ID = createField(DSL.name("source_card_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.graph_sync_error_log.source_card_name</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, String> SOURCE_CARD_NAME = createField(DSL.name("source_card_name"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.graph_sync_error_log.llm_raw_response</code>.
     * 大模型返回的原始异常结果，用于后续微调语料分析
     */
    public final TableField<GraphSyncErrorLogRecord, JSONB> LLM_RAW_RESPONSE = createField(DSL.name("llm_raw_response"), SQLDataType.JSONB, this, "大模型返回的原始异常结果，用于后续微调语料分析");

    /**
     * The column <code>public.graph_sync_error_log.error_type</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, String> ERROR_TYPE = createField(DSL.name("error_type"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.graph_sync_error_log.error_message</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.graph_sync_error_log.resolved</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, Boolean> RESOLVED = createField(DSL.name("resolved"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.graph_sync_error_log.created_at</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.graph_sync_error_log.updated_at</code>.
     */
    public final TableField<GraphSyncErrorLogRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private GraphSyncErrorLog(Name alias, Table<GraphSyncErrorLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GraphSyncErrorLog(Name alias, Table<GraphSyncErrorLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent 图谱抽取错误与幻觉死信队列"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.graph_sync_error_log</code> table
     * reference
     */
    public GraphSyncErrorLog(String alias) {
        this(DSL.name(alias), GRAPH_SYNC_ERROR_LOG);
    }

    /**
     * Create an aliased <code>public.graph_sync_error_log</code> table
     * reference
     */
    public GraphSyncErrorLog(Name alias) {
        this(alias, GRAPH_SYNC_ERROR_LOG);
    }

    /**
     * Create a <code>public.graph_sync_error_log</code> table reference
     */
    public GraphSyncErrorLog() {
        this(DSL.name("graph_sync_error_log"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GraphSyncErrorLogRecord, Long> getIdentity() {
        return (Identity<GraphSyncErrorLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GraphSyncErrorLogRecord> getPrimaryKey() {
        return Keys.GRAPH_SYNC_ERROR_LOG_PKEY;
    }

    @Override
    public GraphSyncErrorLog as(String alias) {
        return new GraphSyncErrorLog(DSL.name(alias), this);
    }

    @Override
    public GraphSyncErrorLog as(Name alias) {
        return new GraphSyncErrorLog(alias, this);
    }

    @Override
    public GraphSyncErrorLog as(Table<?> alias) {
        return new GraphSyncErrorLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GraphSyncErrorLog rename(String name) {
        return new GraphSyncErrorLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GraphSyncErrorLog rename(Name name) {
        return new GraphSyncErrorLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GraphSyncErrorLog rename(Table<?> name) {
        return new GraphSyncErrorLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog where(Condition condition) {
        return new GraphSyncErrorLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GraphSyncErrorLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GraphSyncErrorLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GraphSyncErrorLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GraphSyncErrorLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GraphSyncErrorLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
