/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.records;


import jakarta.annotation.Nullable;

import java.time.ZonedDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.zeroagent.infra.dal.tables.AiTaskCreation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTaskCreationRecord extends UpdatableRecordImpl<AiTaskCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ai_task_creation.id</code>.
     */
    public AiTaskCreationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ai_task_creation.owner_id</code>.
     */
    public AiTaskCreationRecord setOwnerId(@Nullable Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.owner_id</code>.
     */
    @Nullable
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.ai_task_creation.owner_name</code>.
     */
    public AiTaskCreationRecord setOwnerName(@Nullable String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.owner_name</code>.
     */
    @Nullable
    public String getOwnerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ai_task_creation.created_at</code>.
     */
    public AiTaskCreationRecord setCreatedAt(@Nullable ZonedDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.created_at</code>.
     */
    @Nullable
    public ZonedDateTime getCreatedAt() {
        return (ZonedDateTime) get(3);
    }

    /**
     * Setter for <code>public.ai_task_creation.updated_at</code>.
     */
    public AiTaskCreationRecord setUpdatedAt(@Nullable ZonedDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.updated_at</code>.
     */
    @Nullable
    public ZonedDateTime getUpdatedAt() {
        return (ZonedDateTime) get(4);
    }

    /**
     * Setter for <code>public.ai_task_creation.task_name</code>.
     */
    public AiTaskCreationRecord setTaskName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_name</code>.
     */
    public String getTaskName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ai_task_creation.task_type</code>.
     */
    public AiTaskCreationRecord setTaskType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_type</code>.
     */
    public String getTaskType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_status</code>.
     */
    public AiTaskCreationRecord setBizStatus(@Nullable String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_status</code>.
     */
    @Nullable
    public String getBizStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_type</code>.
     */
    public AiTaskCreationRecord setBizType(@Nullable String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_type</code>.
     */
    @Nullable
    public String getBizType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_no</code>.
     */
    public AiTaskCreationRecord setBizNo(@Nullable String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_no</code>.
     */
    @Nullable
    public String getBizNo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.ai_task_creation.sub_biz_no</code>.
     */
    public AiTaskCreationRecord setSubBizNo(@Nullable String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sub_biz_no</code>.
     */
    @Nullable
    public String getSubBizNo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.ai_task_creation.task_status</code>.
     */
    public AiTaskCreationRecord setTaskStatus(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_status</code>.
     */
    public String getTaskStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.ai_task_creation.exec_status</code>.
     */
    public AiTaskCreationRecord setExecStatus(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.exec_status</code>.
     */
    public String getExecStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.ai_task_creation.priority</code>.
     */
    public AiTaskCreationRecord setPriority(@Nullable Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.priority</code>.
     */
    @Nullable
    public Integer getPriority() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.ai_task_creation.sharding</code>.
     */
    public AiTaskCreationRecord setSharding(@Nullable Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sharding</code>.
     */
    @Nullable
    public Integer getSharding() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.ai_task_creation.start_at</code>.
     */
    public AiTaskCreationRecord setStartAt(@Nullable ZonedDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.start_at</code>.
     */
    @Nullable
    public ZonedDateTime getStartAt() {
        return (ZonedDateTime) get(15);
    }

    /**
     * Setter for <code>public.ai_task_creation.finished_at</code>.
     */
    public AiTaskCreationRecord setFinishedAt(@Nullable ZonedDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.finished_at</code>.
     */
    @Nullable
    public ZonedDateTime getFinishedAt() {
        return (ZonedDateTime) get(16);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_params</code>.
     */
    public AiTaskCreationRecord setBizParams(@Nullable JSONB value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_params</code>.
     */
    @Nullable
    public JSONB getBizParams() {
        return (JSONB) get(17);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_exec_info</code>.
     */
    public AiTaskCreationRecord setBizExecInfo(@Nullable JSONB value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_exec_info</code>.
     */
    @Nullable
    public JSONB getBizExecInfo() {
        return (JSONB) get(18);
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_result</code>.
     */
    public AiTaskCreationRecord setBizResult(@Nullable JSONB value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_result</code>.
     */
    @Nullable
    public JSONB getBizResult() {
        return (JSONB) get(19);
    }

    /**
     * Setter for <code>public.ai_task_creation.sys_params</code>.
     */
    public AiTaskCreationRecord setSysParams(@Nullable JSONB value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sys_params</code>.
     */
    @Nullable
    public JSONB getSysParams() {
        return (JSONB) get(20);
    }

    /**
     * Setter for <code>public.ai_task_creation.exec_info</code>.
     */
    public AiTaskCreationRecord setExecInfo(@Nullable JSONB value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.exec_info</code>.
     */
    @Nullable
    public JSONB getExecInfo() {
        return (JSONB) get(21);
    }

    /**
     * Setter for <code>public.ai_task_creation.sys_result</code>.
     */
    public AiTaskCreationRecord setSysResult(@Nullable JSONB value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sys_result</code>.
     */
    @Nullable
    public JSONB getSysResult() {
        return (JSONB) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiTaskCreationRecord
     */
    public AiTaskCreationRecord() {
        super(AiTaskCreation.AI_TASK_CREATION);
    }

    /**
     * Create a detached, initialised AiTaskCreationRecord
     */
    public AiTaskCreationRecord(Long id, @Nullable Long ownerId, @Nullable String ownerName, @Nullable ZonedDateTime createdAt, @Nullable ZonedDateTime updatedAt, String taskName, String taskType, @Nullable String bizStatus, @Nullable String bizType, @Nullable String bizNo, @Nullable String subBizNo, String taskStatus, String execStatus, @Nullable Integer priority, @Nullable Integer sharding, @Nullable ZonedDateTime startAt, @Nullable ZonedDateTime finishedAt, @Nullable JSONB bizParams, @Nullable JSONB bizExecInfo, @Nullable JSONB bizResult, @Nullable JSONB sysParams, @Nullable JSONB execInfo, @Nullable JSONB sysResult) {
        super(AiTaskCreation.AI_TASK_CREATION);

        setId(id);
        setOwnerId(ownerId);
        setOwnerName(ownerName);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setTaskName(taskName);
        setTaskType(taskType);
        setBizStatus(bizStatus);
        setBizType(bizType);
        setBizNo(bizNo);
        setSubBizNo(subBizNo);
        setTaskStatus(taskStatus);
        setExecStatus(execStatus);
        setPriority(priority);
        setSharding(sharding);
        setStartAt(startAt);
        setFinishedAt(finishedAt);
        setBizParams(bizParams);
        setBizExecInfo(bizExecInfo);
        setBizResult(bizResult);
        setSysParams(sysParams);
        setExecInfo(execInfo);
        setSysResult(sysResult);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AiTaskCreationRecord
     */
    public AiTaskCreationRecord(org.zeroagent.infra.dal.tables.pojos.AiTaskCreation value) {
        super(AiTaskCreation.AI_TASK_CREATION);

        if (value != null) {
            setId(value.getId());
            setOwnerId(value.getOwnerId());
            setOwnerName(value.getOwnerName());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setTaskName(value.getTaskName());
            setTaskType(value.getTaskType());
            setBizStatus(value.getBizStatus());
            setBizType(value.getBizType());
            setBizNo(value.getBizNo());
            setSubBizNo(value.getSubBizNo());
            setTaskStatus(value.getTaskStatus());
            setExecStatus(value.getExecStatus());
            setPriority(value.getPriority());
            setSharding(value.getSharding());
            setStartAt(value.getStartAt());
            setFinishedAt(value.getFinishedAt());
            setBizParams(value.getBizParams());
            setBizExecInfo(value.getBizExecInfo());
            setBizResult(value.getBizResult());
            setSysParams(value.getSysParams());
            setExecInfo(value.getExecInfo());
            setSysResult(value.getSysResult());
            resetChangedOnNotNull();
        }
    }
}
