/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.records;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.zeroagent.infra.dal.tables.CardInformationCreation;


/**
 * OCG卡牌基础信息表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardInformationCreationRecord extends UpdatableRecordImpl<CardInformationCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.card_information_creation.id</code>. 雪花算法主键
     */
    public CardInformationCreationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.id</code>. 雪花算法主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.card_information_creation.passcode</code>.
     * 官方8位卡片密码
     */
    public CardInformationCreationRecord setPasscode(@Nullable String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.passcode</code>.
     * 官方8位卡片密码
     */
    @Nullable
    public String getPasscode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.card_information_creation.name</code>. 卡片名称
     */
    public CardInformationCreationRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.name</code>. 卡片名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.card_information_creation.attribution</code>. 属性
     * (光/暗/地/水/炎/风/神)
     */
    public CardInformationCreationRecord setAttribution(@Nullable String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.attribution</code>. 属性
     * (光/暗/地/水/炎/风/神)
     */
    @Nullable
    public String getAttribution() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.card_information_creation.race</code>. 种族
     * (龙/恶魔/魔法师等)
     */
    public CardInformationCreationRecord setRace(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.race</code>. 种族
     * (龙/恶魔/魔法师等)
     */
    @Nullable
    public String getRace() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.card_information_creation.atk</code>. 攻击力 (-1表示?)
     */
    public CardInformationCreationRecord setAtk(@Nullable Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.atk</code>. 攻击力 (-1表示?)
     */
    @Nullable
    public Integer getAtk() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.card_information_creation.def</code>. 守备力 (-1表示?,
     * NULL表示无守备力)
     */
    public CardInformationCreationRecord setDef(@Nullable Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.def</code>. 守备力 (-1表示?,
     * NULL表示无守备力)
     */
    @Nullable
    public Integer getDef() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.card_information_creation.card_type</code>.
     */
    public CardInformationCreationRecord setCardType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.card_type</code>.
     */
    public String getCardType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.card_information_creation.card_subtype</code>.
     * 卡牌特性的JSONB数组
     */
    public CardInformationCreationRecord setCardSubtype(@Nullable JSONB value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.card_subtype</code>.
     * 卡牌特性的JSONB数组
     */
    @Nullable
    public JSONB getCardSubtype() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.card_information_creation.monster_level</code>.
     */
    public CardInformationCreationRecord setMonsterLevel(@Nullable Short value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.monster_level</code>.
     */
    @Nullable
    public Short getMonsterLevel() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.card_information_creation.monster_rank</code>.
     */
    public CardInformationCreationRecord setMonsterRank(@Nullable Short value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.monster_rank</code>.
     */
    @Nullable
    public Short getMonsterRank() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>public.card_information_creation.link_rating</code>.
     */
    public CardInformationCreationRecord setLinkRating(@Nullable Short value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.link_rating</code>.
     */
    @Nullable
    public Short getLinkRating() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>public.card_information_creation.pendulum_scale</code>.
     */
    public CardInformationCreationRecord setPendulumScale(@Nullable Short value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.pendulum_scale</code>.
     */
    @Nullable
    public Short getPendulumScale() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>public.card_information_creation.pendulum_effect</code>.
     * 灵摆区域专有效果
     */
    public CardInformationCreationRecord setPendulumEffect(@Nullable String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.pendulum_effect</code>.
     * 灵摆区域专有效果
     */
    @Nullable
    public String getPendulumEffect() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.card_information_creation.effect</code>.
     */
    public CardInformationCreationRecord setEffect(@Nullable String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.effect</code>.
     */
    @Nullable
    public String getEffect() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.card_information_creation.created_at</code>.
     */
    public CardInformationCreationRecord setCreatedAt(@Nullable OffsetDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.created_at</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(15);
    }

    /**
     * Setter for <code>public.card_information_creation.updated_at</code>.
     */
    public CardInformationCreationRecord setUpdatedAt(@Nullable OffsetDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(16);
    }

    /**
     * Setter for
     * <code>public.card_information_creation.graph_sync_status</code>. 图谱同步状态:
     * 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常
     */
    public CardInformationCreationRecord setGraphSyncStatus(@Nullable Short value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.card_information_creation.graph_sync_status</code>. 图谱同步状态:
     * 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常
     */
    @Nullable
    public Short getGraphSyncStatus() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>public.card_information_creation.biz_response</code>.
     * 存储API返回完整响应体
     */
    public CardInformationCreationRecord setBizResponse(@Nullable JSONB value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.biz_response</code>.
     * 存储API返回完整响应体
     */
    @Nullable
    public JSONB getBizResponse() {
        return (JSONB) get(18);
    }

    /**
     * Setter for <code>public.card_information_creation.archetype</code>.
     * 存储卡牌字段
     */
    public CardInformationCreationRecord setArchetype(@Nullable JSONB value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.archetype</code>.
     * 存储卡牌字段
     */
    @Nullable
    public JSONB getArchetype() {
        return (JSONB) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardInformationCreationRecord
     */
    public CardInformationCreationRecord() {
        super(CardInformationCreation.CARD_INFORMATION_CREATION);
    }

    /**
     * Create a detached, initialised CardInformationCreationRecord
     */
    public CardInformationCreationRecord(Long id, @Nullable String passcode, String name, @Nullable String attribution, @Nullable String race, @Nullable Integer atk, @Nullable Integer def, String cardType, @Nullable JSONB cardSubtype, @Nullable Short monsterLevel, @Nullable Short monsterRank, @Nullable Short linkRating, @Nullable Short pendulumScale, @Nullable String pendulumEffect, @Nullable String effect, @Nullable OffsetDateTime createdAt, @Nullable OffsetDateTime updatedAt, @Nullable Short graphSyncStatus, @Nullable JSONB bizResponse, @Nullable JSONB archetype) {
        super(CardInformationCreation.CARD_INFORMATION_CREATION);

        setId(id);
        setPasscode(passcode);
        setName(name);
        setAttribution(attribution);
        setRace(race);
        setAtk(atk);
        setDef(def);
        setCardType(cardType);
        setCardSubtype(cardSubtype);
        setMonsterLevel(monsterLevel);
        setMonsterRank(monsterRank);
        setLinkRating(linkRating);
        setPendulumScale(pendulumScale);
        setPendulumEffect(pendulumEffect);
        setEffect(effect);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setGraphSyncStatus(graphSyncStatus);
        setBizResponse(bizResponse);
        setArchetype(archetype);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CardInformationCreationRecord
     */
    public CardInformationCreationRecord(org.zeroagent.infra.dal.tables.pojos.CardInformationCreation value) {
        super(CardInformationCreation.CARD_INFORMATION_CREATION);

        if (value != null) {
            setId(value.getId());
            setPasscode(value.getPasscode());
            setName(value.getName());
            setAttribution(value.getAttribution());
            setRace(value.getRace());
            setAtk(value.getAtk());
            setDef(value.getDef());
            setCardType(value.getCardType());
            setCardSubtype(value.getCardSubtype());
            setMonsterLevel(value.getMonsterLevel());
            setMonsterRank(value.getMonsterRank());
            setLinkRating(value.getLinkRating());
            setPendulumScale(value.getPendulumScale());
            setPendulumEffect(value.getPendulumEffect());
            setEffect(value.getEffect());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setGraphSyncStatus(value.getGraphSyncStatus());
            setBizResponse(value.getBizResponse());
            setArchetype(value.getArchetype());
            resetChangedOnNotNull();
        }
    }
}
