/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.records;


import jakarta.annotation.Nullable;

import java.time.ZonedDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.zeroagent.infra.dal.tables.ConversationCreation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationCreationRecord extends UpdatableRecordImpl<ConversationCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.conversation_creation.id</code>.
     */
    public ConversationCreationRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_creation.id</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.conversation_creation.created_at</code>.
     */
    public ConversationCreationRecord setCreatedAt(@Nullable ZonedDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_creation.created_at</code>.
     */
    @Nullable
    public ZonedDateTime getCreatedAt() {
        return (ZonedDateTime) get(1);
    }

    /**
     * Setter for <code>public.conversation_creation.updated_at</code>.
     */
    public ConversationCreationRecord setUpdatedAt(@Nullable ZonedDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_creation.updated_at</code>.
     */
    @Nullable
    public ZonedDateTime getUpdatedAt() {
        return (ZonedDateTime) get(2);
    }

    /**
     * Setter for <code>public.conversation_creation.uid</code>.
     */
    public ConversationCreationRecord setUid(@Nullable Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_creation.uid</code>.
     */
    @Nullable
    public Long getUid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.conversation_creation.title</code>.
     */
    public ConversationCreationRecord setTitle(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_creation.title</code>.
     */
    @Nullable
    public String getTitle() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConversationCreationRecord
     */
    public ConversationCreationRecord() {
        super(ConversationCreation.CONVERSATION_CREATION);
    }

    /**
     * Create a detached, initialised ConversationCreationRecord
     */
    public ConversationCreationRecord(@Nullable Long id, @Nullable ZonedDateTime createdAt, @Nullable ZonedDateTime updatedAt, @Nullable Long uid, @Nullable String title) {
        super(ConversationCreation.CONVERSATION_CREATION);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUid(uid);
        setTitle(title);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ConversationCreationRecord
     */
    public ConversationCreationRecord(org.zeroagent.infra.dal.tables.pojos.ConversationCreation value) {
        super(ConversationCreation.CONVERSATION_CREATION);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setUid(value.getUid());
            setTitle(value.getTitle());
            resetChangedOnNotNull();
        }
    }
}
