/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.records;


import jakarta.annotation.Nullable;

import java.time.ZonedDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationMessageCreationRecord extends UpdatableRecordImpl<ConversationMessageCreationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.conversation_message_creation.id</code>.
     */
    public ConversationMessageCreationRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.id</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.conversation_message_creation.created_at</code>.
     */
    public ConversationMessageCreationRecord setCreatedAt(@Nullable ZonedDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.created_at</code>.
     */
    @Nullable
    public ZonedDateTime getCreatedAt() {
        return (ZonedDateTime) get(1);
    }

    /**
     * Setter for <code>public.conversation_message_creation.updated_at</code>.
     */
    public ConversationMessageCreationRecord setUpdatedAt(@Nullable ZonedDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.updated_at</code>.
     */
    @Nullable
    public ZonedDateTime getUpdatedAt() {
        return (ZonedDateTime) get(2);
    }

    /**
     * Setter for <code>public.conversation_message_creation.uid</code>.
     */
    public ConversationMessageCreationRecord setUid(@Nullable Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.uid</code>.
     */
    @Nullable
    public Long getUid() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>public.conversation_message_creation.conversation_id</code>.
     */
    public ConversationMessageCreationRecord setConversationId(@Nullable Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.conversation_message_creation.conversation_id</code>.
     */
    @Nullable
    public Long getConversationId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.conversation_message_creation.role</code>.
     */
    public ConversationMessageCreationRecord setRole(@Nullable JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.role</code>.
     */
    @Nullable
    public JSONB getRole() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.conversation_message_creation.content</code>.
     */
    public ConversationMessageCreationRecord setContent(@Nullable JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.content</code>.
     */
    @Nullable
    public JSONB getContent() {
        return (JSONB) get(6);
    }

    /**
     * Setter for
     * <code>public.conversation_message_creation.reasoning_content</code>.
     */
    public ConversationMessageCreationRecord setReasoningContent(@Nullable String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.conversation_message_creation.reasoning_content</code>.
     */
    @Nullable
    public String getReasoningContent() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConversationMessageCreationRecord
     */
    public ConversationMessageCreationRecord() {
        super(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION);
    }

    /**
     * Create a detached, initialised ConversationMessageCreationRecord
     */
    public ConversationMessageCreationRecord(@Nullable Long id, @Nullable ZonedDateTime createdAt, @Nullable ZonedDateTime updatedAt, @Nullable Long uid, @Nullable Long conversationId, @Nullable JSONB role, @Nullable JSONB content, @Nullable String reasoningContent) {
        super(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUid(uid);
        setConversationId(conversationId);
        setRole(role);
        setContent(content);
        setReasoningContent(reasoningContent);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ConversationMessageCreationRecord
     */
    public ConversationMessageCreationRecord(org.zeroagent.infra.dal.tables.pojos.ConversationMessageCreation value) {
        super(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setUid(value.getUid());
            setConversationId(value.getConversationId());
            setRole(value.getRole());
            setContent(value.getContent());
            setReasoningContent(value.getReasoningContent());
            resetChangedOnNotNull();
        }
    }
}
