/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.records;


import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.zeroagent.infra.dal.tables.GraphSyncErrorLog;


/**
 * Agent 图谱抽取错误与幻觉死信队列
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GraphSyncErrorLogRecord extends UpdatableRecordImpl<GraphSyncErrorLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.graph_sync_error_log.id</code>.
     */
    public GraphSyncErrorLogRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.id</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.source_card_id</code>.
     */
    public GraphSyncErrorLogRecord setSourceCardId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.source_card_id</code>.
     */
    public Long getSourceCardId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.source_card_name</code>.
     */
    public GraphSyncErrorLogRecord setSourceCardName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.source_card_name</code>.
     */
    public String getSourceCardName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.llm_raw_response</code>.
     * 大模型返回的原始异常结果，用于后续微调语料分析
     */
    public GraphSyncErrorLogRecord setLlmRawResponse(@Nullable JSONB value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.llm_raw_response</code>.
     * 大模型返回的原始异常结果，用于后续微调语料分析
     */
    @Nullable
    public JSONB getLlmRawResponse() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.error_type</code>.
     */
    public GraphSyncErrorLogRecord setErrorType(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.error_type</code>.
     */
    @Nullable
    public String getErrorType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.error_message</code>.
     */
    public GraphSyncErrorLogRecord setErrorMessage(@Nullable String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.error_message</code>.
     */
    @Nullable
    public String getErrorMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.resolved</code>.
     */
    public GraphSyncErrorLogRecord setResolved(@Nullable Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.resolved</code>.
     */
    @Nullable
    public Boolean getResolved() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.created_at</code>.
     */
    public GraphSyncErrorLogRecord setCreatedAt(@Nullable OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.created_at</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.graph_sync_error_log.updated_at</code>.
     */
    public GraphSyncErrorLogRecord setUpdatedAt(@Nullable OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraphSyncErrorLogRecord
     */
    public GraphSyncErrorLogRecord() {
        super(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG);
    }

    /**
     * Create a detached, initialised GraphSyncErrorLogRecord
     */
    public GraphSyncErrorLogRecord(@Nullable Long id, Long sourceCardId, String sourceCardName, @Nullable JSONB llmRawResponse, @Nullable String errorType, @Nullable String errorMessage, @Nullable Boolean resolved, @Nullable OffsetDateTime createdAt, @Nullable OffsetDateTime updatedAt) {
        super(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG);

        setId(id);
        setSourceCardId(sourceCardId);
        setSourceCardName(sourceCardName);
        setLlmRawResponse(llmRawResponse);
        setErrorType(errorType);
        setErrorMessage(errorMessage);
        setResolved(resolved);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GraphSyncErrorLogRecord
     */
    public GraphSyncErrorLogRecord(org.zeroagent.infra.dal.tables.pojos.GraphSyncErrorLog value) {
        super(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG);

        if (value != null) {
            setId(value.getId());
            setSourceCardId(value.getSourceCardId());
            setSourceCardName(value.getSourceCardName());
            setLlmRawResponse(value.getLlmRawResponse());
            setErrorType(value.getErrorType());
            setErrorMessage(value.getErrorMessage());
            setResolved(value.getResolved());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
