/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.zeroagent.infra.dal.tables.CardInformationCreation;
import org.zeroagent.infra.dal.tables.ConversationCreation;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;


/**
 * A class modelling indexes of tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CARD_INFO_PASSCODE = Internal.createIndex(DSL.name("idx_card_info_passcode"), CardInformationCreation.CARD_INFORMATION_CREATION, new OrderField[] { CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE }, false);
    public static final Index IDX_CARD_INFO_SYNC_STATUS = Internal.createIndex(DSL.name("idx_card_info_sync_status"), CardInformationCreation.CARD_INFORMATION_CREATION, new OrderField[] { CardInformationCreation.CARD_INFORMATION_CREATION.GRAPH_SYNC_STATUS }, false);
    public static final Index IDX_CONVERSATION_CREATION_UID = Internal.createIndex(DSL.name("idx_conversation_creation_uid"), ConversationCreation.CONVERSATION_CREATION, new OrderField[] { ConversationCreation.CONVERSATION_CREATION.UID }, false);
    public static final Index IDX_CONVERSATION_MESSAGE_CREATION_ID = Internal.createIndex(DSL.name("idx_conversation_message_creation_id"), ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION, new OrderField[] { ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.CONVERSATION_ID }, false);
    public static final Index IDX_CONVERSATION_MESSAGE_CREATION_UID = Internal.createIndex(DSL.name("idx_conversation_message_creation_uid"), ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION, new OrderField[] { ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.UID }, false);
    public static final Index TRGM_IDX_CARD_NAME = Internal.createIndex(DSL.name("trgm_idx_card_name"), CardInformationCreation.CARD_INFORMATION_CREATION, new OrderField[] { CardInformationCreation.CARD_INFORMATION_CREATION.NAME }, false);
}
