/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal;


import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.zeroagent.infra.dal.tables.AiTaskCreation;
import org.zeroagent.infra.dal.tables.CardInformationCreation;
import org.zeroagent.infra.dal.tables.ConversationCreation;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;
import org.zeroagent.infra.dal.tables.GraphSyncErrorLog;
import org.zeroagent.infra.dal.tables.records.AiTaskCreationRecord;
import org.zeroagent.infra.dal.tables.records.CardInformationCreationRecord;
import org.zeroagent.infra.dal.tables.records.ConversationCreationRecord;
import org.zeroagent.infra.dal.tables.records.ConversationMessageCreationRecord;
import org.zeroagent.infra.dal.tables.records.GraphSyncErrorLogRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AiTaskCreationRecord> AI_TASK_CREATION_PKEY = Internal.createUniqueKey(AiTaskCreation.AI_TASK_CREATION, DSL.name("ai_task_creation_pkey"), new TableField[] { AiTaskCreation.AI_TASK_CREATION.ID }, true);
    public static final UniqueKey<CardInformationCreationRecord> CARD_INFORMATION_CREATION_PASSCODE_KEY = Internal.createUniqueKey(CardInformationCreation.CARD_INFORMATION_CREATION, DSL.name("card_information_creation_passcode_key"), new TableField[] { CardInformationCreation.CARD_INFORMATION_CREATION.PASSCODE }, true);
    public static final UniqueKey<CardInformationCreationRecord> CARD_INFORMATION_CREATION_PKEY = Internal.createUniqueKey(CardInformationCreation.CARD_INFORMATION_CREATION, DSL.name("card_information_creation_pkey"), new TableField[] { CardInformationCreation.CARD_INFORMATION_CREATION.ID }, true);
    public static final UniqueKey<ConversationCreationRecord> CONVERSATION_CREATION_PKEY = Internal.createUniqueKey(ConversationCreation.CONVERSATION_CREATION, DSL.name("conversation_creation_pkey"), new TableField[] { ConversationCreation.CONVERSATION_CREATION.ID }, true);
    public static final UniqueKey<ConversationMessageCreationRecord> CONVERSATION_MESSAGE_CREATION_PKEY = Internal.createUniqueKey(ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION, DSL.name("conversation_message_creation_pkey"), new TableField[] { ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION.ID }, true);
    public static final UniqueKey<GraphSyncErrorLogRecord> GRAPH_SYNC_ERROR_LOG_PKEY = Internal.createUniqueKey(GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG, DSL.name("graph_sync_error_log_pkey"), new TableField[] { GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG.ID }, true);
}
