/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.zeroagent.infra.dal.tables.AiTaskCreation;
import org.zeroagent.infra.dal.tables.CardInformationCreation;
import org.zeroagent.infra.dal.tables.ConversationCreation;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;
import org.zeroagent.infra.dal.tables.GraphSyncErrorLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ai_task_creation</code>.
     */
    public final AiTaskCreation AI_TASK_CREATION = AiTaskCreation.AI_TASK_CREATION;

    /**
     * OCG卡牌基础信息表
     */
    public final CardInformationCreation CARD_INFORMATION_CREATION = CardInformationCreation.CARD_INFORMATION_CREATION;

    /**
     * The table <code>public.conversation_creation</code>.
     */
    public final ConversationCreation CONVERSATION_CREATION = ConversationCreation.CONVERSATION_CREATION;

    /**
     * The table <code>public.conversation_message_creation</code>.
     */
    public final ConversationMessageCreation CONVERSATION_MESSAGE_CREATION = ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION;

    /**
     * Agent 图谱抽取错误与幻觉死信队列
     */
    public final GraphSyncErrorLog GRAPH_SYNC_ERROR_LOG = GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AiTaskCreation.AI_TASK_CREATION,
            CardInformationCreation.CARD_INFORMATION_CREATION,
            ConversationCreation.CONVERSATION_CREATION,
            ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION,
            GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG
        );
    }
}
