/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal;


import javax.annotation.processing.Generated;

import org.zeroagent.infra.dal.tables.AiTaskCreation;
import org.zeroagent.infra.dal.tables.CardInformationCreation;
import org.zeroagent.infra.dal.tables.ConversationCreation;
import org.zeroagent.infra.dal.tables.ConversationMessageCreation;
import org.zeroagent.infra.dal.tables.GraphSyncErrorLog;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.ai_task_creation</code>.
     */
    public static final AiTaskCreation AI_TASK_CREATION = AiTaskCreation.AI_TASK_CREATION;

    /**
     * OCG卡牌基础信息表
     */
    public static final CardInformationCreation CARD_INFORMATION_CREATION = CardInformationCreation.CARD_INFORMATION_CREATION;

    /**
     * The table <code>public.conversation_creation</code>.
     */
    public static final ConversationCreation CONVERSATION_CREATION = ConversationCreation.CONVERSATION_CREATION;

    /**
     * The table <code>public.conversation_message_creation</code>.
     */
    public static final ConversationMessageCreation CONVERSATION_MESSAGE_CREATION = ConversationMessageCreation.CONVERSATION_MESSAGE_CREATION;

    /**
     * Agent 图谱抽取错误与幻觉死信队列
     */
    public static final GraphSyncErrorLog GRAPH_SYNC_ERROR_LOG = GraphSyncErrorLog.GRAPH_SYNC_ERROR_LOG;
}
