CREATE TABLE IF NOT EXISTS conversation_message_creation (
                                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                             created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                                                             updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                                                             uid BIGINT NOT NULL,
                                                             conversation_id BIGINT NOT NULL,
                                                             role JSONB NOT NULL,
                                                             content JSONB NOT NULL
);
CREATE INDEX idx_conversation_message_creation_id ON conversation_message_creation(conversation_id);
CREATE INDEX idx_conversation_message_creation_uid ON conversation_message_creation(uid);