/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.pojos;


import jakarta.annotation.Nullable;

import java.io.Serializable;
import java.time.ZonedDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTaskCreation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long ownerId;
    private String ownerName;
    private ZonedDateTime createdAt;
    private ZonedDateTime updatedAt;
    private String taskName;
    private String taskType;
    private String bizStatus;
    private String bizType;
    private String bizNo;
    private String subBizNo;
    private String taskStatus;
    private String execStatus;
    private Integer priority;
    private Integer sharding;
    private ZonedDateTime startAt;
    private ZonedDateTime finishedAt;
    private JSONB bizParams;
    private JSONB bizExecInfo;
    private JSONB bizResult;
    private JSONB sysParams;
    private JSONB execInfo;
    private JSONB sysResult;

    public AiTaskCreation() {}

    public AiTaskCreation(AiTaskCreation value) {
        this.id = value.id;
        this.ownerId = value.ownerId;
        this.ownerName = value.ownerName;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.taskName = value.taskName;
        this.taskType = value.taskType;
        this.bizStatus = value.bizStatus;
        this.bizType = value.bizType;
        this.bizNo = value.bizNo;
        this.subBizNo = value.subBizNo;
        this.taskStatus = value.taskStatus;
        this.execStatus = value.execStatus;
        this.priority = value.priority;
        this.sharding = value.sharding;
        this.startAt = value.startAt;
        this.finishedAt = value.finishedAt;
        this.bizParams = value.bizParams;
        this.bizExecInfo = value.bizExecInfo;
        this.bizResult = value.bizResult;
        this.sysParams = value.sysParams;
        this.execInfo = value.execInfo;
        this.sysResult = value.sysResult;
    }

    public AiTaskCreation(
        Long id,
        @Nullable Long ownerId,
        @Nullable String ownerName,
        @Nullable ZonedDateTime createdAt,
        @Nullable ZonedDateTime updatedAt,
        String taskName,
        String taskType,
        @Nullable String bizStatus,
        @Nullable String bizType,
        @Nullable String bizNo,
        @Nullable String subBizNo,
        String taskStatus,
        String execStatus,
        @Nullable Integer priority,
        @Nullable Integer sharding,
        @Nullable ZonedDateTime startAt,
        @Nullable ZonedDateTime finishedAt,
        @Nullable JSONB bizParams,
        @Nullable JSONB bizExecInfo,
        @Nullable JSONB bizResult,
        @Nullable JSONB sysParams,
        @Nullable JSONB execInfo,
        @Nullable JSONB sysResult
    ) {
        this.id = id;
        this.ownerId = ownerId;
        this.ownerName = ownerName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.taskName = taskName;
        this.taskType = taskType;
        this.bizStatus = bizStatus;
        this.bizType = bizType;
        this.bizNo = bizNo;
        this.subBizNo = subBizNo;
        this.taskStatus = taskStatus;
        this.execStatus = execStatus;
        this.priority = priority;
        this.sharding = sharding;
        this.startAt = startAt;
        this.finishedAt = finishedAt;
        this.bizParams = bizParams;
        this.bizExecInfo = bizExecInfo;
        this.bizResult = bizResult;
        this.sysParams = sysParams;
        this.execInfo = execInfo;
        this.sysResult = sysResult;
    }

    /**
     * Getter for <code>public.ai_task_creation.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ai_task_creation.id</code>.
     */
    public AiTaskCreation setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.owner_id</code>.
     */
    @Nullable
    public Long getOwnerId() {
        return this.ownerId;
    }

    /**
     * Setter for <code>public.ai_task_creation.owner_id</code>.
     */
    public AiTaskCreation setOwnerId(@Nullable Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.owner_name</code>.
     */
    @Nullable
    public String getOwnerName() {
        return this.ownerName;
    }

    /**
     * Setter for <code>public.ai_task_creation.owner_name</code>.
     */
    public AiTaskCreation setOwnerName(@Nullable String ownerName) {
        this.ownerName = ownerName;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.created_at</code>.
     */
    @Nullable
    public ZonedDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.ai_task_creation.created_at</code>.
     */
    public AiTaskCreation setCreatedAt(@Nullable ZonedDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.updated_at</code>.
     */
    @Nullable
    public ZonedDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.ai_task_creation.updated_at</code>.
     */
    public AiTaskCreation setUpdatedAt(@Nullable ZonedDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_name</code>.
     */
    public String getTaskName() {
        return this.taskName;
    }

    /**
     * Setter for <code>public.ai_task_creation.task_name</code>.
     */
    public AiTaskCreation setTaskName(String taskName) {
        this.taskName = taskName;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_type</code>.
     */
    public String getTaskType() {
        return this.taskType;
    }

    /**
     * Setter for <code>public.ai_task_creation.task_type</code>.
     */
    public AiTaskCreation setTaskType(String taskType) {
        this.taskType = taskType;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_status</code>.
     */
    @Nullable
    public String getBizStatus() {
        return this.bizStatus;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_status</code>.
     */
    public AiTaskCreation setBizStatus(@Nullable String bizStatus) {
        this.bizStatus = bizStatus;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_type</code>.
     */
    @Nullable
    public String getBizType() {
        return this.bizType;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_type</code>.
     */
    public AiTaskCreation setBizType(@Nullable String bizType) {
        this.bizType = bizType;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_no</code>.
     */
    @Nullable
    public String getBizNo() {
        return this.bizNo;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_no</code>.
     */
    public AiTaskCreation setBizNo(@Nullable String bizNo) {
        this.bizNo = bizNo;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sub_biz_no</code>.
     */
    @Nullable
    public String getSubBizNo() {
        return this.subBizNo;
    }

    /**
     * Setter for <code>public.ai_task_creation.sub_biz_no</code>.
     */
    public AiTaskCreation setSubBizNo(@Nullable String subBizNo) {
        this.subBizNo = subBizNo;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.task_status</code>.
     */
    public String getTaskStatus() {
        return this.taskStatus;
    }

    /**
     * Setter for <code>public.ai_task_creation.task_status</code>.
     */
    public AiTaskCreation setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.exec_status</code>.
     */
    public String getExecStatus() {
        return this.execStatus;
    }

    /**
     * Setter for <code>public.ai_task_creation.exec_status</code>.
     */
    public AiTaskCreation setExecStatus(String execStatus) {
        this.execStatus = execStatus;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.priority</code>.
     */
    @Nullable
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Setter for <code>public.ai_task_creation.priority</code>.
     */
    public AiTaskCreation setPriority(@Nullable Integer priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sharding</code>.
     */
    @Nullable
    public Integer getSharding() {
        return this.sharding;
    }

    /**
     * Setter for <code>public.ai_task_creation.sharding</code>.
     */
    public AiTaskCreation setSharding(@Nullable Integer sharding) {
        this.sharding = sharding;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.start_at</code>.
     */
    @Nullable
    public ZonedDateTime getStartAt() {
        return this.startAt;
    }

    /**
     * Setter for <code>public.ai_task_creation.start_at</code>.
     */
    public AiTaskCreation setStartAt(@Nullable ZonedDateTime startAt) {
        this.startAt = startAt;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.finished_at</code>.
     */
    @Nullable
    public ZonedDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.ai_task_creation.finished_at</code>.
     */
    public AiTaskCreation setFinishedAt(@Nullable ZonedDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_params</code>.
     */
    @Nullable
    public JSONB getBizParams() {
        return this.bizParams;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_params</code>.
     */
    public AiTaskCreation setBizParams(@Nullable JSONB bizParams) {
        this.bizParams = bizParams;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_exec_info</code>.
     */
    @Nullable
    public JSONB getBizExecInfo() {
        return this.bizExecInfo;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_exec_info</code>.
     */
    public AiTaskCreation setBizExecInfo(@Nullable JSONB bizExecInfo) {
        this.bizExecInfo = bizExecInfo;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.biz_result</code>.
     */
    @Nullable
    public JSONB getBizResult() {
        return this.bizResult;
    }

    /**
     * Setter for <code>public.ai_task_creation.biz_result</code>.
     */
    public AiTaskCreation setBizResult(@Nullable JSONB bizResult) {
        this.bizResult = bizResult;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sys_params</code>.
     */
    @Nullable
    public JSONB getSysParams() {
        return this.sysParams;
    }

    /**
     * Setter for <code>public.ai_task_creation.sys_params</code>.
     */
    public AiTaskCreation setSysParams(@Nullable JSONB sysParams) {
        this.sysParams = sysParams;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.exec_info</code>.
     */
    @Nullable
    public JSONB getExecInfo() {
        return this.execInfo;
    }

    /**
     * Setter for <code>public.ai_task_creation.exec_info</code>.
     */
    public AiTaskCreation setExecInfo(@Nullable JSONB execInfo) {
        this.execInfo = execInfo;
        return this;
    }

    /**
     * Getter for <code>public.ai_task_creation.sys_result</code>.
     */
    @Nullable
    public JSONB getSysResult() {
        return this.sysResult;
    }

    /**
     * Setter for <code>public.ai_task_creation.sys_result</code>.
     */
    public AiTaskCreation setSysResult(@Nullable JSONB sysResult) {
        this.sysResult = sysResult;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AiTaskCreation other = (AiTaskCreation) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ownerId == null) {
            if (other.ownerId != null)
                return false;
        }
        else if (!this.ownerId.equals(other.ownerId))
            return false;
        if (this.ownerName == null) {
            if (other.ownerName != null)
                return false;
        }
        else if (!this.ownerName.equals(other.ownerName))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.taskName == null) {
            if (other.taskName != null)
                return false;
        }
        else if (!this.taskName.equals(other.taskName))
            return false;
        if (this.taskType == null) {
            if (other.taskType != null)
                return false;
        }
        else if (!this.taskType.equals(other.taskType))
            return false;
        if (this.bizStatus == null) {
            if (other.bizStatus != null)
                return false;
        }
        else if (!this.bizStatus.equals(other.bizStatus))
            return false;
        if (this.bizType == null) {
            if (other.bizType != null)
                return false;
        }
        else if (!this.bizType.equals(other.bizType))
            return false;
        if (this.bizNo == null) {
            if (other.bizNo != null)
                return false;
        }
        else if (!this.bizNo.equals(other.bizNo))
            return false;
        if (this.subBizNo == null) {
            if (other.subBizNo != null)
                return false;
        }
        else if (!this.subBizNo.equals(other.subBizNo))
            return false;
        if (this.taskStatus == null) {
            if (other.taskStatus != null)
                return false;
        }
        else if (!this.taskStatus.equals(other.taskStatus))
            return false;
        if (this.execStatus == null) {
            if (other.execStatus != null)
                return false;
        }
        else if (!this.execStatus.equals(other.execStatus))
            return false;
        if (this.priority == null) {
            if (other.priority != null)
                return false;
        }
        else if (!this.priority.equals(other.priority))
            return false;
        if (this.sharding == null) {
            if (other.sharding != null)
                return false;
        }
        else if (!this.sharding.equals(other.sharding))
            return false;
        if (this.startAt == null) {
            if (other.startAt != null)
                return false;
        }
        else if (!this.startAt.equals(other.startAt))
            return false;
        if (this.finishedAt == null) {
            if (other.finishedAt != null)
                return false;
        }
        else if (!this.finishedAt.equals(other.finishedAt))
            return false;
        if (this.bizParams == null) {
            if (other.bizParams != null)
                return false;
        }
        else if (!this.bizParams.equals(other.bizParams))
            return false;
        if (this.bizExecInfo == null) {
            if (other.bizExecInfo != null)
                return false;
        }
        else if (!this.bizExecInfo.equals(other.bizExecInfo))
            return false;
        if (this.bizResult == null) {
            if (other.bizResult != null)
                return false;
        }
        else if (!this.bizResult.equals(other.bizResult))
            return false;
        if (this.sysParams == null) {
            if (other.sysParams != null)
                return false;
        }
        else if (!this.sysParams.equals(other.sysParams))
            return false;
        if (this.execInfo == null) {
            if (other.execInfo != null)
                return false;
        }
        else if (!this.execInfo.equals(other.execInfo))
            return false;
        if (this.sysResult == null) {
            if (other.sysResult != null)
                return false;
        }
        else if (!this.sysResult.equals(other.sysResult))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ownerId == null) ? 0 : this.ownerId.hashCode());
        result = prime * result + ((this.ownerName == null) ? 0 : this.ownerName.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.taskName == null) ? 0 : this.taskName.hashCode());
        result = prime * result + ((this.taskType == null) ? 0 : this.taskType.hashCode());
        result = prime * result + ((this.bizStatus == null) ? 0 : this.bizStatus.hashCode());
        result = prime * result + ((this.bizType == null) ? 0 : this.bizType.hashCode());
        result = prime * result + ((this.bizNo == null) ? 0 : this.bizNo.hashCode());
        result = prime * result + ((this.subBizNo == null) ? 0 : this.subBizNo.hashCode());
        result = prime * result + ((this.taskStatus == null) ? 0 : this.taskStatus.hashCode());
        result = prime * result + ((this.execStatus == null) ? 0 : this.execStatus.hashCode());
        result = prime * result + ((this.priority == null) ? 0 : this.priority.hashCode());
        result = prime * result + ((this.sharding == null) ? 0 : this.sharding.hashCode());
        result = prime * result + ((this.startAt == null) ? 0 : this.startAt.hashCode());
        result = prime * result + ((this.finishedAt == null) ? 0 : this.finishedAt.hashCode());
        result = prime * result + ((this.bizParams == null) ? 0 : this.bizParams.hashCode());
        result = prime * result + ((this.bizExecInfo == null) ? 0 : this.bizExecInfo.hashCode());
        result = prime * result + ((this.bizResult == null) ? 0 : this.bizResult.hashCode());
        result = prime * result + ((this.sysParams == null) ? 0 : this.sysParams.hashCode());
        result = prime * result + ((this.execInfo == null) ? 0 : this.execInfo.hashCode());
        result = prime * result + ((this.sysResult == null) ? 0 : this.sysResult.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AiTaskCreation (");

        sb.append(id);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(taskName);
        sb.append(", ").append(taskType);
        sb.append(", ").append(bizStatus);
        sb.append(", ").append(bizType);
        sb.append(", ").append(bizNo);
        sb.append(", ").append(subBizNo);
        sb.append(", ").append(taskStatus);
        sb.append(", ").append(execStatus);
        sb.append(", ").append(priority);
        sb.append(", ").append(sharding);
        sb.append(", ").append(startAt);
        sb.append(", ").append(finishedAt);
        sb.append(", ").append(bizParams);
        sb.append(", ").append(bizExecInfo);
        sb.append(", ").append(bizResult);
        sb.append(", ").append(sysParams);
        sb.append(", ").append(execInfo);
        sb.append(", ").append(sysResult);

        sb.append(")");
        return sb.toString();
    }
}
