/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.pojos;


import jakarta.annotation.Nullable;

import java.io.Serializable;
import java.time.ZonedDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * OCG卡牌基础信息表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardInformationCreation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String passcode;
    private String name;
    private String attribution;
    private String race;
    private Integer atk;
    private Integer def;
    private String cardType;
    private JSONB cardSubtype;
    private Short monsterLevel;
    private Short monsterRank;
    private Short linkRating;
    private Short pendulumScale;
    private String pendulumEffect;
    private String effect;
    private ZonedDateTime createdAt;
    private ZonedDateTime updatedAt;
    private Short graphSyncStatus;
    private JSONB bizResponse;
    private JSONB archetype;

    public CardInformationCreation() {}

    public CardInformationCreation(CardInformationCreation value) {
        this.id = value.id;
        this.passcode = value.passcode;
        this.name = value.name;
        this.attribution = value.attribution;
        this.race = value.race;
        this.atk = value.atk;
        this.def = value.def;
        this.cardType = value.cardType;
        this.cardSubtype = value.cardSubtype;
        this.monsterLevel = value.monsterLevel;
        this.monsterRank = value.monsterRank;
        this.linkRating = value.linkRating;
        this.pendulumScale = value.pendulumScale;
        this.pendulumEffect = value.pendulumEffect;
        this.effect = value.effect;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.graphSyncStatus = value.graphSyncStatus;
        this.bizResponse = value.bizResponse;
        this.archetype = value.archetype;
    }

    public CardInformationCreation(
        Long id,
        @Nullable String passcode,
        String name,
        @Nullable String attribution,
        @Nullable String race,
        @Nullable Integer atk,
        @Nullable Integer def,
        String cardType,
        @Nullable JSONB cardSubtype,
        @Nullable Short monsterLevel,
        @Nullable Short monsterRank,
        @Nullable Short linkRating,
        @Nullable Short pendulumScale,
        @Nullable String pendulumEffect,
        @Nullable String effect,
        @Nullable ZonedDateTime createdAt,
        @Nullable ZonedDateTime updatedAt,
        @Nullable Short graphSyncStatus,
        @Nullable JSONB bizResponse,
        @Nullable JSONB archetype
    ) {
        this.id = id;
        this.passcode = passcode;
        this.name = name;
        this.attribution = attribution;
        this.race = race;
        this.atk = atk;
        this.def = def;
        this.cardType = cardType;
        this.cardSubtype = cardSubtype;
        this.monsterLevel = monsterLevel;
        this.monsterRank = monsterRank;
        this.linkRating = linkRating;
        this.pendulumScale = pendulumScale;
        this.pendulumEffect = pendulumEffect;
        this.effect = effect;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.graphSyncStatus = graphSyncStatus;
        this.bizResponse = bizResponse;
        this.archetype = archetype;
    }

    /**
     * Getter for <code>public.card_information_creation.id</code>. 雪花算法主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.card_information_creation.id</code>. 雪花算法主键
     */
    public CardInformationCreation setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.passcode</code>.
     * 官方8位卡片密码
     */
    @Nullable
    public String getPasscode() {
        return this.passcode;
    }

    /**
     * Setter for <code>public.card_information_creation.passcode</code>.
     * 官方8位卡片密码
     */
    public CardInformationCreation setPasscode(@Nullable String passcode) {
        this.passcode = passcode;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.name</code>. 卡片名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.card_information_creation.name</code>. 卡片名称
     */
    public CardInformationCreation setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.attribution</code>. 属性
     * (光/暗/地/水/炎/风/神)
     */
    @Nullable
    public String getAttribution() {
        return this.attribution;
    }

    /**
     * Setter for <code>public.card_information_creation.attribution</code>. 属性
     * (光/暗/地/水/炎/风/神)
     */
    public CardInformationCreation setAttribution(@Nullable String attribution) {
        this.attribution = attribution;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.race</code>. 种族
     * (龙/恶魔/魔法师等)
     */
    @Nullable
    public String getRace() {
        return this.race;
    }

    /**
     * Setter for <code>public.card_information_creation.race</code>. 种族
     * (龙/恶魔/魔法师等)
     */
    public CardInformationCreation setRace(@Nullable String race) {
        this.race = race;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.atk</code>. 攻击力 (-1表示?)
     */
    @Nullable
    public Integer getAtk() {
        return this.atk;
    }

    /**
     * Setter for <code>public.card_information_creation.atk</code>. 攻击力 (-1表示?)
     */
    public CardInformationCreation setAtk(@Nullable Integer atk) {
        this.atk = atk;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.def</code>. 守备力 (-1表示?,
     * NULL表示无守备力)
     */
    @Nullable
    public Integer getDef() {
        return this.def;
    }

    /**
     * Setter for <code>public.card_information_creation.def</code>. 守备力 (-1表示?,
     * NULL表示无守备力)
     */
    public CardInformationCreation setDef(@Nullable Integer def) {
        this.def = def;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.card_type</code>.
     */
    public String getCardType() {
        return this.cardType;
    }

    /**
     * Setter for <code>public.card_information_creation.card_type</code>.
     */
    public CardInformationCreation setCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.card_subtype</code>.
     * 卡牌特性的JSONB数组
     */
    @Nullable
    public JSONB getCardSubtype() {
        return this.cardSubtype;
    }

    /**
     * Setter for <code>public.card_information_creation.card_subtype</code>.
     * 卡牌特性的JSONB数组
     */
    public CardInformationCreation setCardSubtype(@Nullable JSONB cardSubtype) {
        this.cardSubtype = cardSubtype;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.monster_level</code>.
     */
    @Nullable
    public Short getMonsterLevel() {
        return this.monsterLevel;
    }

    /**
     * Setter for <code>public.card_information_creation.monster_level</code>.
     */
    public CardInformationCreation setMonsterLevel(@Nullable Short monsterLevel) {
        this.monsterLevel = monsterLevel;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.monster_rank</code>.
     */
    @Nullable
    public Short getMonsterRank() {
        return this.monsterRank;
    }

    /**
     * Setter for <code>public.card_information_creation.monster_rank</code>.
     */
    public CardInformationCreation setMonsterRank(@Nullable Short monsterRank) {
        this.monsterRank = monsterRank;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.link_rating</code>.
     */
    @Nullable
    public Short getLinkRating() {
        return this.linkRating;
    }

    /**
     * Setter for <code>public.card_information_creation.link_rating</code>.
     */
    public CardInformationCreation setLinkRating(@Nullable Short linkRating) {
        this.linkRating = linkRating;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.pendulum_scale</code>.
     */
    @Nullable
    public Short getPendulumScale() {
        return this.pendulumScale;
    }

    /**
     * Setter for <code>public.card_information_creation.pendulum_scale</code>.
     */
    public CardInformationCreation setPendulumScale(@Nullable Short pendulumScale) {
        this.pendulumScale = pendulumScale;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.pendulum_effect</code>.
     * 灵摆区域专有效果
     */
    @Nullable
    public String getPendulumEffect() {
        return this.pendulumEffect;
    }

    /**
     * Setter for <code>public.card_information_creation.pendulum_effect</code>.
     * 灵摆区域专有效果
     */
    public CardInformationCreation setPendulumEffect(@Nullable String pendulumEffect) {
        this.pendulumEffect = pendulumEffect;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.effect</code>.
     */
    @Nullable
    public String getEffect() {
        return this.effect;
    }

    /**
     * Setter for <code>public.card_information_creation.effect</code>.
     */
    public CardInformationCreation setEffect(@Nullable String effect) {
        this.effect = effect;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.created_at</code>.
     */
    @Nullable
    public ZonedDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.card_information_creation.created_at</code>.
     */
    public CardInformationCreation setCreatedAt(@Nullable ZonedDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.updated_at</code>.
     */
    @Nullable
    public ZonedDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.card_information_creation.updated_at</code>.
     */
    public CardInformationCreation setUpdatedAt(@Nullable ZonedDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for
     * <code>public.card_information_creation.graph_sync_status</code>. 图谱同步状态:
     * 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常
     */
    @Nullable
    public Short getGraphSyncStatus() {
        return this.graphSyncStatus;
    }

    /**
     * Setter for
     * <code>public.card_information_creation.graph_sync_status</code>. 图谱同步状态:
     * 0-待处理, 1-处理中, 2-已同步, 3-正常结束, 4-解析异常
     */
    public CardInformationCreation setGraphSyncStatus(@Nullable Short graphSyncStatus) {
        this.graphSyncStatus = graphSyncStatus;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.biz_response</code>.
     * 存储API返回完整响应体
     */
    @Nullable
    public JSONB getBizResponse() {
        return this.bizResponse;
    }

    /**
     * Setter for <code>public.card_information_creation.biz_response</code>.
     * 存储API返回完整响应体
     */
    public CardInformationCreation setBizResponse(@Nullable JSONB bizResponse) {
        this.bizResponse = bizResponse;
        return this;
    }

    /**
     * Getter for <code>public.card_information_creation.archetype</code>.
     * 存储卡牌字段
     */
    @Nullable
    public JSONB getArchetype() {
        return this.archetype;
    }

    /**
     * Setter for <code>public.card_information_creation.archetype</code>.
     * 存储卡牌字段
     */
    public CardInformationCreation setArchetype(@Nullable JSONB archetype) {
        this.archetype = archetype;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CardInformationCreation other = (CardInformationCreation) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.passcode == null) {
            if (other.passcode != null)
                return false;
        }
        else if (!this.passcode.equals(other.passcode))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.attribution == null) {
            if (other.attribution != null)
                return false;
        }
        else if (!this.attribution.equals(other.attribution))
            return false;
        if (this.race == null) {
            if (other.race != null)
                return false;
        }
        else if (!this.race.equals(other.race))
            return false;
        if (this.atk == null) {
            if (other.atk != null)
                return false;
        }
        else if (!this.atk.equals(other.atk))
            return false;
        if (this.def == null) {
            if (other.def != null)
                return false;
        }
        else if (!this.def.equals(other.def))
            return false;
        if (this.cardType == null) {
            if (other.cardType != null)
                return false;
        }
        else if (!this.cardType.equals(other.cardType))
            return false;
        if (this.cardSubtype == null) {
            if (other.cardSubtype != null)
                return false;
        }
        else if (!this.cardSubtype.equals(other.cardSubtype))
            return false;
        if (this.monsterLevel == null) {
            if (other.monsterLevel != null)
                return false;
        }
        else if (!this.monsterLevel.equals(other.monsterLevel))
            return false;
        if (this.monsterRank == null) {
            if (other.monsterRank != null)
                return false;
        }
        else if (!this.monsterRank.equals(other.monsterRank))
            return false;
        if (this.linkRating == null) {
            if (other.linkRating != null)
                return false;
        }
        else if (!this.linkRating.equals(other.linkRating))
            return false;
        if (this.pendulumScale == null) {
            if (other.pendulumScale != null)
                return false;
        }
        else if (!this.pendulumScale.equals(other.pendulumScale))
            return false;
        if (this.pendulumEffect == null) {
            if (other.pendulumEffect != null)
                return false;
        }
        else if (!this.pendulumEffect.equals(other.pendulumEffect))
            return false;
        if (this.effect == null) {
            if (other.effect != null)
                return false;
        }
        else if (!this.effect.equals(other.effect))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.graphSyncStatus == null) {
            if (other.graphSyncStatus != null)
                return false;
        }
        else if (!this.graphSyncStatus.equals(other.graphSyncStatus))
            return false;
        if (this.bizResponse == null) {
            if (other.bizResponse != null)
                return false;
        }
        else if (!this.bizResponse.equals(other.bizResponse))
            return false;
        if (this.archetype == null) {
            if (other.archetype != null)
                return false;
        }
        else if (!this.archetype.equals(other.archetype))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.passcode == null) ? 0 : this.passcode.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.attribution == null) ? 0 : this.attribution.hashCode());
        result = prime * result + ((this.race == null) ? 0 : this.race.hashCode());
        result = prime * result + ((this.atk == null) ? 0 : this.atk.hashCode());
        result = prime * result + ((this.def == null) ? 0 : this.def.hashCode());
        result = prime * result + ((this.cardType == null) ? 0 : this.cardType.hashCode());
        result = prime * result + ((this.cardSubtype == null) ? 0 : this.cardSubtype.hashCode());
        result = prime * result + ((this.monsterLevel == null) ? 0 : this.monsterLevel.hashCode());
        result = prime * result + ((this.monsterRank == null) ? 0 : this.monsterRank.hashCode());
        result = prime * result + ((this.linkRating == null) ? 0 : this.linkRating.hashCode());
        result = prime * result + ((this.pendulumScale == null) ? 0 : this.pendulumScale.hashCode());
        result = prime * result + ((this.pendulumEffect == null) ? 0 : this.pendulumEffect.hashCode());
        result = prime * result + ((this.effect == null) ? 0 : this.effect.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.graphSyncStatus == null) ? 0 : this.graphSyncStatus.hashCode());
        result = prime * result + ((this.bizResponse == null) ? 0 : this.bizResponse.hashCode());
        result = prime * result + ((this.archetype == null) ? 0 : this.archetype.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CardInformationCreation (");

        sb.append(id);
        sb.append(", ").append(passcode);
        sb.append(", ").append(name);
        sb.append(", ").append(attribution);
        sb.append(", ").append(race);
        sb.append(", ").append(atk);
        sb.append(", ").append(def);
        sb.append(", ").append(cardType);
        sb.append(", ").append(cardSubtype);
        sb.append(", ").append(monsterLevel);
        sb.append(", ").append(monsterRank);
        sb.append(", ").append(linkRating);
        sb.append(", ").append(pendulumScale);
        sb.append(", ").append(pendulumEffect);
        sb.append(", ").append(effect);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(graphSyncStatus);
        sb.append(", ").append(bizResponse);
        sb.append(", ").append(archetype);

        sb.append(")");
        return sb.toString();
    }
}
