/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.pojos;


import jakarta.annotation.Nullable;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationMessageCreation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private Long uid;
    private Long conversationId;
    private JSONB role;
    private JSONB content;
    private String reasoningContent;

    public ConversationMessageCreation() {}

    public ConversationMessageCreation(ConversationMessageCreation value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.uid = value.uid;
        this.conversationId = value.conversationId;
        this.role = value.role;
        this.content = value.content;
        this.reasoningContent = value.reasoningContent;
    }

    public ConversationMessageCreation(
        @Nullable Long id,
        @Nullable OffsetDateTime createdAt,
        @Nullable OffsetDateTime updatedAt,
        @Nullable Long uid,
        @Nullable Long conversationId,
        @Nullable JSONB role,
        @Nullable JSONB content,
        @Nullable String reasoningContent
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.uid = uid;
        this.conversationId = conversationId;
        this.role = role;
        this.content = content;
        this.reasoningContent = reasoningContent;
    }

    /**
     * Getter for <code>public.conversation_message_creation.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.conversation_message_creation.id</code>.
     */
    public ConversationMessageCreation setId(@Nullable Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.created_at</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.conversation_message_creation.created_at</code>.
     */
    public ConversationMessageCreation setCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.conversation_message_creation.updated_at</code>.
     */
    public ConversationMessageCreation setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.uid</code>.
     */
    @Nullable
    public Long getUid() {
        return this.uid;
    }

    /**
     * Setter for <code>public.conversation_message_creation.uid</code>.
     */
    public ConversationMessageCreation setUid(@Nullable Long uid) {
        this.uid = uid;
        return this;
    }

    /**
     * Getter for
     * <code>public.conversation_message_creation.conversation_id</code>.
     */
    @Nullable
    public Long getConversationId() {
        return this.conversationId;
    }

    /**
     * Setter for
     * <code>public.conversation_message_creation.conversation_id</code>.
     */
    public ConversationMessageCreation setConversationId(@Nullable Long conversationId) {
        this.conversationId = conversationId;
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.role</code>.
     */
    @Nullable
    public JSONB getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.conversation_message_creation.role</code>.
     */
    public ConversationMessageCreation setRole(@Nullable JSONB role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>public.conversation_message_creation.content</code>.
     */
    @Nullable
    public JSONB getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.conversation_message_creation.content</code>.
     */
    public ConversationMessageCreation setContent(@Nullable JSONB content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for
     * <code>public.conversation_message_creation.reasoning_content</code>.
     */
    @Nullable
    public String getReasoningContent() {
        return this.reasoningContent;
    }

    /**
     * Setter for
     * <code>public.conversation_message_creation.reasoning_content</code>.
     */
    public ConversationMessageCreation setReasoningContent(@Nullable String reasoningContent) {
        this.reasoningContent = reasoningContent;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ConversationMessageCreation other = (ConversationMessageCreation) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.uid == null) {
            if (other.uid != null)
                return false;
        }
        else if (!this.uid.equals(other.uid))
            return false;
        if (this.conversationId == null) {
            if (other.conversationId != null)
                return false;
        }
        else if (!this.conversationId.equals(other.conversationId))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.reasoningContent == null) {
            if (other.reasoningContent != null)
                return false;
        }
        else if (!this.reasoningContent.equals(other.reasoningContent))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.uid == null) ? 0 : this.uid.hashCode());
        result = prime * result + ((this.conversationId == null) ? 0 : this.conversationId.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.reasoningContent == null) ? 0 : this.reasoningContent.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConversationMessageCreation (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(uid);
        sb.append(", ").append(conversationId);
        sb.append(", ").append(role);
        sb.append(", ").append(content);
        sb.append(", ").append(reasoningContent);

        sb.append(")");
        return sb.toString();
    }
}
