/*
 * This file is generated by jOOQ.
 */
package org.zeroagent.infra.dal.tables.pojos;


import jakarta.annotation.Nullable;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * Agent 图谱抽取错误与幻觉死信队列
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GraphSyncErrorLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long sourceCardId;
    private String sourceCardName;
    private JSONB llmRawResponse;
    private String errorType;
    private String errorMessage;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private Short status;
    private Long targetCardId;
    private String targetCardName;

    public GraphSyncErrorLog() {}

    public GraphSyncErrorLog(GraphSyncErrorLog value) {
        this.id = value.id;
        this.sourceCardId = value.sourceCardId;
        this.sourceCardName = value.sourceCardName;
        this.llmRawResponse = value.llmRawResponse;
        this.errorType = value.errorType;
        this.errorMessage = value.errorMessage;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
        this.targetCardId = value.targetCardId;
        this.targetCardName = value.targetCardName;
    }

    public GraphSyncErrorLog(
        Long id,
        Long sourceCardId,
        String sourceCardName,
        @Nullable JSONB llmRawResponse,
        @Nullable String errorType,
        @Nullable String errorMessage,
        @Nullable OffsetDateTime createdAt,
        @Nullable OffsetDateTime updatedAt,
        @Nullable Short status,
        @Nullable Long targetCardId,
        @Nullable String targetCardName
    ) {
        this.id = id;
        this.sourceCardId = sourceCardId;
        this.sourceCardName = sourceCardName;
        this.llmRawResponse = llmRawResponse;
        this.errorType = errorType;
        this.errorMessage = errorMessage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.status = status;
        this.targetCardId = targetCardId;
        this.targetCardName = targetCardName;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.id</code>.
     */
    public GraphSyncErrorLog setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.source_card_id</code>.
     */
    public Long getSourceCardId() {
        return this.sourceCardId;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.source_card_id</code>.
     */
    public GraphSyncErrorLog setSourceCardId(Long sourceCardId) {
        this.sourceCardId = sourceCardId;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.source_card_name</code>.
     */
    public String getSourceCardName() {
        return this.sourceCardName;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.source_card_name</code>.
     */
    public GraphSyncErrorLog setSourceCardName(String sourceCardName) {
        this.sourceCardName = sourceCardName;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.llm_raw_response</code>.
     * 大模型返回的原始异常结果，用于后续微调语料分析
     */
    @Nullable
    public JSONB getLlmRawResponse() {
        return this.llmRawResponse;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.llm_raw_response</code>.
     * 大模型返回的原始异常结果，用于后续微调语料分析
     */
    public GraphSyncErrorLog setLlmRawResponse(@Nullable JSONB llmRawResponse) {
        this.llmRawResponse = llmRawResponse;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.error_type</code>.
     */
    @Nullable
    public String getErrorType() {
        return this.errorType;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.error_type</code>.
     */
    public GraphSyncErrorLog setErrorType(@Nullable String errorType) {
        this.errorType = errorType;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.error_message</code>.
     */
    @Nullable
    public String getErrorMessage() {
        return this.errorMessage;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.error_message</code>.
     */
    public GraphSyncErrorLog setErrorMessage(@Nullable String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.created_at</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.created_at</code>.
     */
    public GraphSyncErrorLog setCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.updated_at</code>.
     */
    public GraphSyncErrorLog setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.status</code>.
     */
    @Nullable
    public Short getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.status</code>.
     */
    public GraphSyncErrorLog setStatus(@Nullable Short status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.target_card_id</code>.
     */
    @Nullable
    public Long getTargetCardId() {
        return this.targetCardId;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.target_card_id</code>.
     */
    public GraphSyncErrorLog setTargetCardId(@Nullable Long targetCardId) {
        this.targetCardId = targetCardId;
        return this;
    }

    /**
     * Getter for <code>public.graph_sync_error_log.target_card_name</code>.
     */
    @Nullable
    public String getTargetCardName() {
        return this.targetCardName;
    }

    /**
     * Setter for <code>public.graph_sync_error_log.target_card_name</code>.
     */
    public GraphSyncErrorLog setTargetCardName(@Nullable String targetCardName) {
        this.targetCardName = targetCardName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GraphSyncErrorLog other = (GraphSyncErrorLog) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.sourceCardId == null) {
            if (other.sourceCardId != null)
                return false;
        }
        else if (!this.sourceCardId.equals(other.sourceCardId))
            return false;
        if (this.sourceCardName == null) {
            if (other.sourceCardName != null)
                return false;
        }
        else if (!this.sourceCardName.equals(other.sourceCardName))
            return false;
        if (this.llmRawResponse == null) {
            if (other.llmRawResponse != null)
                return false;
        }
        else if (!this.llmRawResponse.equals(other.llmRawResponse))
            return false;
        if (this.errorType == null) {
            if (other.errorType != null)
                return false;
        }
        else if (!this.errorType.equals(other.errorType))
            return false;
        if (this.errorMessage == null) {
            if (other.errorMessage != null)
                return false;
        }
        else if (!this.errorMessage.equals(other.errorMessage))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.targetCardId == null) {
            if (other.targetCardId != null)
                return false;
        }
        else if (!this.targetCardId.equals(other.targetCardId))
            return false;
        if (this.targetCardName == null) {
            if (other.targetCardName != null)
                return false;
        }
        else if (!this.targetCardName.equals(other.targetCardName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.sourceCardId == null) ? 0 : this.sourceCardId.hashCode());
        result = prime * result + ((this.sourceCardName == null) ? 0 : this.sourceCardName.hashCode());
        result = prime * result + ((this.llmRawResponse == null) ? 0 : this.llmRawResponse.hashCode());
        result = prime * result + ((this.errorType == null) ? 0 : this.errorType.hashCode());
        result = prime * result + ((this.errorMessage == null) ? 0 : this.errorMessage.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.targetCardId == null) ? 0 : this.targetCardId.hashCode());
        result = prime * result + ((this.targetCardName == null) ? 0 : this.targetCardName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GraphSyncErrorLog (");

        sb.append(id);
        sb.append(", ").append(sourceCardId);
        sb.append(", ").append(sourceCardName);
        sb.append(", ").append(llmRawResponse);
        sb.append(", ").append(errorType);
        sb.append(", ").append(errorMessage);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);
        sb.append(", ").append(targetCardId);
        sb.append(", ").append(targetCardName);

        sb.append(")");
        return sb.toString();
    }
}
